CONFIG_SPI=y
CONFIG_GPIO=y

# Enable float support in printf (picolibc)
CONFIG_PICOLIBC_IO_FLOAT=y

# Logging
# CONFIG_LOG=y
# CONFIG_LOG_DEFAULT_LEVEL=4

# Console / early debug
CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_PRINTK=y
CONFIG_PRINTK=y
CONFIG_EARLY_CONSOLE=y

# # Better crash info on RISC-V
# CONFIG_EXCEPTION_DEBUG=y
# CONFIG_ASSERT=y
# CONFIG_ASSERT_VERBOSE=y
