"""Emit a multi-model main.c that runs N models sequentially and prints
each one's output + per-kernel profile between marker lines tagged with
the model name.

This is the orchestrator file the harness_multi/ CMakeLists.txt builds
into the binary. The single-model harness's main.c lives in
harness/src/main.c and is unchanged; this script's output is its
multi-model counterpart.

Usage:
    python -m modelblaster.pipeline.generate_multi_main \\
        --models name1:/abs/path/to/model_dir1 name2:/abs/path/to/model_dir2 \\
        --out  /abs/path/to/multi_main.c
"""

from __future__ import annotations

import argparse
import json
import os


HEADER = "/* @generated by modelblaster/pipeline/generate_multi_main.py — do not edit. */"


def _ir_for(model_dir: str) -> dict:
    """Locate graph.json for a model_dir (search the dir, then its parent)."""
    for cand in (
        os.path.join(model_dir, "graph.json"),
        os.path.join(os.path.dirname(model_dir.rstrip("/")), "graph.json"),
    ):
        if os.path.exists(cand):
            with open(cand) as f:
                return json.load(f)
    raise FileNotFoundError(f"could not find graph.json near {model_dir}")


def _emit(models: list[tuple[str, str]],
          pool_sizes: list[int] | None = None) -> str:
    """Render multi_main.c source. `models` is a list of (name, model_dir).

    If `pool_sizes` is provided, each model runs once per pool size; the
    output blocks are tagged `[<model>@p<N>]`. Each iteration tears down
    and re-creates the modelblaster_pool so the per-op profile records reflect
    that exact pool width. Useful for collecting topo_0 / topo_0_1 /
    topo_0_1_2_3 results in a single FireSim run, amortizing the
    infrasetup + flash + boot overhead.

    If `pool_sizes` is None, falls back to the original single-pass
    behavior: each model runs once, output blocks tagged just
    `[<model>]`. The pool is created once at start of main.
    """
    inc_lines: list[str] = []
    buf_decls: list[str] = []
    for name, model_dir in models:
        umid = name.replace(".", "_").replace("-", "_").upper()
        mid = name.replace(".", "_").replace("-", "_")
        inc_lines.append(f'#include "{name}_model.h"')
        inc_lines.append(f'#include "{name}_test_io.h"')
        buf_decls.append(
            f"static model_{mid}_output_t out_{mid}[MODEL_{umid}_OUTPUT_SIZE];"
        )

    def _per_model_run_block(name: str, tag: str) -> str:
        """The OUTPUT/PROFILE/WALL print sequence for one (model, tag)
        pair. `tag` is what shows up between [] in the output markers —
        either the bare model name or `<model>@p<N>` in pool-sweep mode."""
        umid = name.replace(".", "_").replace("-", "_").upper()
        mid = name.replace(".", "_").replace("-", "_")
        return f"""\
    /* --- {tag} ----------------------------------------------------------- */
    printf("running model: {tag}\\n");
    model_{mid}_reset_profile();
    run_model_{mid}(model_{mid}_test_input, out_{mid}, (void *)pool);
    /* In-binary golden compare. Both arrays widen to float so the
     * same loop handles f32, f16, and integer outputs. Replaces the
     * per-element printf dump that used to dominate FireSim runtime
     * for kernelbench-shaped tensors. Host gates on
     *   (max_abs_err <= atol) || (max_rel_err <= rtol)
     * which is a sufficient PASS condition for the numpy.allclose-style
     * tolerance the runner expects. */
    {{
        float max_abs_err = 0.0f;
        float max_rel_err = 0.0f;
        for (int i = 0; i < MODEL_{umid}_TEST_OUTPUT_LEN; i++) {{
            float a = (float)out_{mid}[i];
            float g = (float)model_{mid}_test_golden[i];
            float ae = a > g ? a - g : g - a;
            float ag = g > 0.0f ? g : -g;
            float re = ae / (ag > 1e-12f ? ag : 1e-12f);
            if (ae > max_abs_err) max_abs_err = ae;
            if (re > max_rel_err) max_rel_err = re;
        }}
        printf("=== MODELBLASTER_VERIFY [{tag}] === "
               "max_abs_err=%.9g max_rel_err=%.9g n=%d\\n",
               (double)max_abs_err, (double)max_rel_err,
               MODEL_{umid}_TEST_OUTPUT_LEN);
    }}
    {{
        int n_records = 0;
        const model_{mid}_op_record_t *records =
            model_{mid}_profile_records(&n_records);
        printf("=== MODELBLASTER_PROFILE_BEGIN [{tag}] ===\\n");
        printf("dispatch_id,name,op,shape,cycles\\n");
        for (int i = 0; i < n_records; i++) {{
            printf("%d,%s,%s,%s,%lu\\n",
                   records[i].dispatch_id,
                   records[i].name, records[i].op, records[i].shape,
                   records[i].cycles);
        }}
        printf("=== MODELBLASTER_PROFILE_END [{tag}] ===\\n");
    }}
    printf("=== MODELBLASTER_WALL_CYCLES [{tag}] === %lu\\n",
           model_{mid}_wall_cycles());
"""

    run_blocks: list[str] = []
    if not pool_sizes:
        # Original behavior: single pool created in main(); each model
        # runs once tagged with its bare name.
        for name, _ in models:
            run_blocks.append(_per_model_run_block(name, name))
    else:
        # Pool-sweep: outer loop over pool sizes recreates the pool per
        # iteration; inner loop runs every model under that pool. Tag
        # looks like `<model>@p<N>` so the host runner can split per-N
        # results.csv files.
        for ps in pool_sizes:
            ps_block_parts = [
                f"""\
    /* === pool_size = {ps} ============================================ */
    modelblaster_pool_destroy(pool);
    pool = modelblaster_pool_create({ps});
    if (pool == NULL && {ps} > 0) {{
        printf("FATAL: modelblaster_pool_create({ps}) returned NULL\\n");
        sys_reboot(SYS_REBOOT_COLD);
        return -1;
    }}
    printf("modelblaster_pool resized to %u workers\\n",
           (unsigned)modelblaster_pool_get_threads_count(pool));
"""
            ]
            for name, _ in models:
                ps_block_parts.append(_per_model_run_block(name, f"{name}@p{ps}"))
            run_blocks.append("\n".join(ps_block_parts))

    return f"""{HEADER}
/*
 * Multi-model harness entry point. Runs each model sequentially on its own
 * fixed test input, prints output + per-kernel profile between marker lines
 * tagged with the model name so the host-side spike_runner can disambiguate.
 *
 * MODELBLASTER_DISABLE_UNMANGLED prevents each model's model.h from defining
 * unmangled aliases (run_model, model_input_t, MODEL_NAME, ...) that would
 * collide across models.
 *
 * The harness owns a single modelblaster_pool. It's created here and threaded
 * through every run_model_<name>() call so per-op kernels can dispatch
 * work onto it (intra-model parallelism). Kernels that are still
 * sequential simply ignore the handle.
 */

#define MODELBLASTER_DISABLE_UNMANGLED

#include <stdio.h>
#include <stdlib.h>
#include "modelblaster_pool.h"
#include <zephyr/sys/reboot.h>

{chr(10).join(inc_lines)}

{chr(10).join(buf_decls)}

int main(void)
{{
    printf("modelblaster multi-model harness: %d models on %s\\n",
           {len(models)}, CONFIG_BOARD_TARGET);

    /* MODELBLASTER_POOL_THREADS lets the build pick a fixed worker count; 0
     * (the default) makes modelblaster_pool_create return NULL and the
     * generated parallel_<op> wrappers fall back to a sequential kernel
     * call. The sweep harness sets this per-run to compare 1- vs
     * N-thread costs.
     */
#ifndef MODELBLASTER_POOL_THREADS
#define MODELBLASTER_POOL_THREADS 0
#endif
    modelblaster_pool_t pool = modelblaster_pool_create(MODELBLASTER_POOL_THREADS);
    if (pool == NULL && MODELBLASTER_POOL_THREADS > 0) {{
        printf("FATAL: modelblaster_pool_create returned NULL\\n");
        sys_reboot(SYS_REBOOT_COLD);
        return -1;
    }}
    printf("modelblaster_pool: %u threads\\n",
           (unsigned)modelblaster_pool_get_threads_count(pool));

{chr(10).join(run_blocks)}

    modelblaster_pool_destroy(pool);
    sys_reboot(SYS_REBOOT_COLD);
    return 0;
}}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--models", required=True, nargs="+",
                    help="<name>:<model_dir> pairs (model_dir = the per-target "
                         "generated/<target>/ dir that holds model.c, kernels.c, "
                         "weights.c, model.h, test_io.h)")
    ap.add_argument("--out", required=True, help="path for the emitted multi_main.c")
    ap.add_argument("--pool-sizes", default=None,
                    help="comma-separated pool sizes to sweep (e.g. '1,2,4'). "
                         "When set, the generated main runs each model once "
                         "per pool size; output blocks are tagged "
                         "[<model>@p<N>]. Default: single run per model with "
                         "MODELBLASTER_POOL_THREADS-defaulted pool.")
    args = ap.parse_args()

    pairs: list[tuple[str, str]] = []
    for spec in args.models:
        if ":" not in spec:
            raise SystemExit(f"--models entry must be name:dir, got {spec!r}")
        name, model_dir = spec.split(":", 1)
        if not os.path.isdir(model_dir):
            raise SystemExit(f"model_dir does not exist: {model_dir}")
        ir = _ir_for(model_dir)
        ir_name = ir.get("name")
        if ir_name and ir_name != name:
            raise SystemExit(
                f"name mismatch: --models said {name!r} but graph.json "
                f"records {ir_name!r} for {model_dir}"
            )
        pairs.append((name, model_dir))

    pool_sizes = None
    if args.pool_sizes:
        pool_sizes = [int(p) for p in args.pool_sizes.split(",") if p.strip()]
        if any(p < 1 for p in pool_sizes):
            raise SystemExit(f"--pool-sizes must be positive integers")

    src = _emit(pairs, pool_sizes=pool_sizes)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(src)
    if pool_sizes:
        print(f"wrote {args.out}  ({len(pairs)} models × {len(pool_sizes)} "
              f"pool sizes = {len(pairs)*len(pool_sizes)} runs)")
    else:
        print(f"wrote {args.out}  ({len(pairs)} models)")


if __name__ == "__main__":
    main()
