"""Schedule-JSON ingest -> validated schedule + C dispatch table.

XPU-RT emits a `schedule.json` describing how each dispatch should
execute on a given core registry. This module:

  1. Loads the JSON, applies defaults, and resolves it against the
     IR (graph.json) and the core registry (modelblaster/cores/*.json).
  2. Validates: every dispatch_id is covered, every assigned core
     supports the dispatch's op, all `depends_on` ids exist, no
     cycles, the partial order respects the IR's data dependencies.
  3. Emits a static C dispatch table (`<model>_dispatch_table.h/.c`)
     the runtime can walk. Today the table is for tooling consumption
     only (schedule-driven runtime is a follow-up); the data is shaped
     so a runtime stub can switch on `core_kind` per entry to route
     to the right worker queue.

Schedule JSON schema (informal):

    {
      "model": "<must match graph.json's name>",
      "registry": "<must match registry's system tag>",
      "dispatches": [
        {
          "dispatch_id": <int>,
          "core": "<core name from registry>",   // hard placement
          "depends_on": [<dispatch_id>...],       // optional; default = IR's deps
          "priority": <int>,                       // optional; default 0
          "start_time": <int|null>,                // optional; cycles since model start. null = "as soon as deps resolve"
          "comment": "<optional free-form>"
        },
        ...
      ]
    }

The core field is the *name* (not kind) so XPU-RT can distinguish
e.g. rocket0 from rocket1. Use "any" to defer placement to the
runtime — the codegen treats those as available on every matching
core.
"""

from __future__ import annotations

import argparse
import json
import os
from dataclasses import dataclass
from typing import Optional

from modelblaster.pipeline import core_registry


HEADER = "/* @generated by modelblaster/pipeline/ingest_schedule.py — do not edit. */"


@dataclass
class DispatchPlacement:
    dispatch_id: int
    core: str               # "any" or a core name from the registry
    depends_on: tuple[int, ...]
    priority: int
    start_time: Optional[int]
    op: str                 # echo from IR (for codegen + debug)
    name: str               # echo from IR


@dataclass
class Schedule:
    model: str
    registry_system: str
    placements: tuple[DispatchPlacement, ...]


def _ir_dispatch_index(ir: dict) -> dict[int, dict]:
    """Build dispatch_id -> op record."""
    out: dict[int, dict] = {}
    for op in ir.get("ops", []):
        did = op.get("dispatch_id")
        if did is not None:
            out[did] = op
    return out


def load(schedule_path: str, ir: dict, reg: core_registry.CoreRegistry) -> Schedule:
    """Load + validate. Raises ValueError on any inconsistency."""
    with open(schedule_path) as f:
        doc = json.load(f)

    if doc.get("model") and doc["model"] != ir.get("name"):
        raise ValueError(
            f"schedule.model={doc['model']!r} != ir.name={ir.get('name')!r}")
    if doc.get("registry") and doc["registry"] != reg.system:
        raise ValueError(
            f"schedule.registry={doc['registry']!r} != "
            f"registry.system={reg.system!r}")

    ir_dispatches = _ir_dispatch_index(ir)
    valid_targets = {"any"} | reg.names()

    raw = doc.get("dispatches")
    if not isinstance(raw, list) or not raw:
        raise ValueError(f"{schedule_path}: 'dispatches' must be a non-empty list")

    placements: list[DispatchPlacement] = []
    seen_ids: set[int] = set()
    for entry in raw:
        did = entry.get("dispatch_id")
        if did is None:
            raise ValueError(f"{schedule_path}: every entry needs a dispatch_id")
        if did not in ir_dispatches:
            raise ValueError(
                f"schedule references dispatch_id={did} but IR has no such dispatch")
        if did in seen_ids:
            raise ValueError(f"schedule lists dispatch_id={did} twice")
        seen_ids.add(did)

        op = ir_dispatches[did]
        core = entry.get("core", "any")
        if core not in valid_targets:
            raise ValueError(
                f"dispatch {did}: core={core!r} not in registry "
                f"{sorted(valid_targets)}")
        if not reg.resolve_target(core, op["op"]):
            raise ValueError(
                f"dispatch {did} (op={op['op']}): core={core!r} cannot "
                f"execute this op (capability mismatch)")

        # Default depends_on = IR's data-flow dependencies. XPU-RT may
        # add ordering constraints (e.g. for resource-shared cores) —
        # those must be a *superset* of the IR deps; we never relax.
        ir_deps = set(op.get("depends_on", []))
        sched_deps_raw = entry.get("depends_on")
        if sched_deps_raw is None:
            deps = tuple(sorted(ir_deps))
        else:
            sched_deps = set(sched_deps_raw)
            missing = ir_deps - sched_deps
            if missing:
                raise ValueError(
                    f"dispatch {did}: schedule.depends_on={sorted(sched_deps)} "
                    f"drops IR data deps {sorted(missing)}")
            for d in sched_deps:
                if d not in ir_dispatches:
                    raise ValueError(
                        f"dispatch {did}: depends_on references unknown id {d}")
            deps = tuple(sorted(sched_deps))

        placements.append(DispatchPlacement(
            dispatch_id=did,
            core=core,
            depends_on=deps,
            priority=int(entry.get("priority", 0)),
            start_time=entry.get("start_time"),
            op=op["op"],
            name=op.get("name", f"dispatch_{did}"),
        ))

    # Coverage: every IR dispatch must appear in the schedule.
    missing = set(ir_dispatches.keys()) - seen_ids
    if missing:
        raise ValueError(
            f"schedule misses {len(missing)} dispatch(es) from IR: "
            f"{sorted(missing)[:10]}{'...' if len(missing) > 10 else ''}")

    # Cycle check (Kahn) using schedule.depends_on as edges.
    indeg = {p.dispatch_id: 0 for p in placements}
    children: dict[int, list[int]] = {p.dispatch_id: [] for p in placements}
    for p in placements:
        for d in p.depends_on:
            children[d].append(p.dispatch_id)
            indeg[p.dispatch_id] += 1
    q = [d for d, n in indeg.items() if n == 0]
    visited = 0
    while q:
        d = q.pop()
        visited += 1
        for c in children[d]:
            indeg[c] -= 1
            if indeg[c] == 0:
                q.append(c)
    if visited != len(placements):
        raise ValueError(
            "schedule has a dependency cycle (Kahn ran out before "
            "visiting all dispatches)")

    placements.sort(key=lambda p: p.dispatch_id)
    return Schedule(
        model=ir.get("name", ""),
        registry_system=reg.system,
        placements=tuple(placements),
    )


def emit_dispatch_table(sched: Schedule,
                        reg: core_registry.CoreRegistry,
                        out_dir: str) -> tuple[str, str]:
    """Emit <model>_dispatch_table.h and .c carrying the schedule as a
    static C array. The runtime can `#include` the header to walk the
    table; today's runtime ignores it (collapses to one pthreadpool).

    Returns (header_path, source_path)."""
    mid = sched.model.replace(".", "_").replace("-", "_")
    umid = mid.upper()
    n = len(sched.placements)

    # Build per-dispatch deps arrays.
    deps_arrays: list[str] = []
    for p in sched.placements:
        if p.depends_on:
            arr = ", ".join(str(d) for d in p.depends_on)
            deps_arrays.append(
                f"static const int dispatch_{p.dispatch_id}_deps[] = "
                f"{{ {arr} }};"
            )
        else:
            deps_arrays.append(
                f"#define dispatch_{p.dispatch_id}_deps NULL"
            )

    # Look up each placement's resolved core kind for the codegen.
    core_kind_for: dict[str, str] = {c.name: c.kind for c in reg.cores}

    table_rows: list[str] = []
    for p in sched.placements:
        if p.core == "any":
            kind = "any"
            hart = -1
        else:
            kind = core_kind_for[p.core]
            harts = reg.by_name[p.core].harts
            hart = harts[0] if harts else -1
        n_deps = len(p.depends_on)
        deps_ref = (f"dispatch_{p.dispatch_id}_deps" if n_deps else "NULL")
        start = p.start_time if p.start_time is not None else -1
        table_rows.append(
            f'    {{ .dispatch_id = {p.dispatch_id}, '
            f'.op = "{p.op}", .name = "{p.name}", '
            f'.core_name = "{p.core}", .core_kind = "{kind}", .hart = {hart}, '
            f'.priority = {p.priority}, .start_time = {start}, '
            f'.n_deps = {n_deps}, .deps = {deps_ref} }},'
        )

    h_path = os.path.join(out_dir, f"{mid}_dispatch_table.h")
    c_path = os.path.join(out_dir, f"{mid}_dispatch_table.c")

    h = f"""{HEADER}
#pragma once

#include <stddef.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* One entry per IR dispatch (non-view ops). The table is laid out in
 * dispatch_id order; the runtime is responsible for honoring
 * `deps[]` before invoking. */
typedef struct {{
    int            dispatch_id;
    const char    *op;          /* IR op kind, e.g. "linear" */
    const char    *name;        /* IR node name, e.g. "mlp.0" */
    const char    *core_name;   /* registry core name; "any" if unbound */
    const char    *core_kind;   /* registry kind; "any" if unbound */
    int            hart;         /* preferred hart, or -1 if unbound */
    int            priority;
    int            start_time;  /* cycles from start; -1 = "as deps resolve" */
    int            n_deps;
    const int     *deps;        /* dispatch_ids that must complete first */
}} model_{mid}_dispatch_entry_t;

#define MODEL_{umid}_N_DISPATCHES   {n}
#define MODEL_{umid}_SCHEDULE_SYS   "{sched.registry_system}"

extern const model_{mid}_dispatch_entry_t
    MODEL_{umid}_DISPATCH_TABLE[MODEL_{umid}_N_DISPATCHES];

#ifdef __cplusplus
}}
#endif
"""
    with open(h_path, "w") as f:
        f.write(h)

    c = f"""{HEADER}
#include <stddef.h>
#include "{mid}_dispatch_table.h"

{chr(10).join(deps_arrays)}

const model_{mid}_dispatch_entry_t
MODEL_{umid}_DISPATCH_TABLE[MODEL_{umid}_N_DISPATCHES] = {{
{chr(10).join(table_rows)}
}};
"""
    with open(c_path, "w") as f:
        f.write(c)

    return h_path, c_path


# --- CLI ----------------------------------------------------------------

def _main() -> None:
    ap = argparse.ArgumentParser(
        description="Validate a schedule.json + emit a C dispatch table.")
    ap.add_argument("--ir", required=True, help="path to graph.json")
    ap.add_argument("--registry", required=True, help="path to a cores/*.json")
    ap.add_argument("--schedule", required=True, help="path to schedule.json")
    ap.add_argument("--out-dir", required=True,
                    help="directory to drop <model>_dispatch_table.{h,c}")
    args = ap.parse_args()

    ir = json.load(open(args.ir))
    reg = core_registry.load(args.registry)
    sched = load(args.schedule, ir, reg)
    os.makedirs(args.out_dir, exist_ok=True)
    h, c = emit_dispatch_table(sched, reg, args.out_dir)
    print(f"schedule ok: {len(sched.placements)} dispatches, "
          f"system={sched.registry_system}")
    print(f"wrote {h}")
    print(f"wrote {c}")


if __name__ == "__main__":
    _main()
