"""Ingest an XPU-RT-emitted schedule.json -> combined C dispatch table.

XPU-RT's schedule is a multi-network table:

    {
      "dot_file": "...",
      "dispatches": {
        "<job_name>_dispatch_<id>": {
          "id": <int>,
          "ordinal": 1, "total": 1,
          "dependencies": ["<other key>", ...],   // intra-job data deps
          "hardware_target": "CPU_P#0" | "CPU_E#0",
          "start_time": <ms>, "duration": <ms>,
          "job_name": "dronet" | "mlp_control0" | ...,
          "module_name": "...",
          "time_dependency": "<other key>"          // optional cross-job edge
        }, ...
      }
    }

This module:

  1. Parses the schedule, groups dispatches by job_name.
  2. Validates each (job_name, id) against the corresponding model's
     graph.json — the id must reference a real dispatch in the IR.
     Multiple instances of the same network (e.g. mlp_control0..5) all
     share one IR.
  3. Resolves the cross-job time_dependency field — the scheduler can
     issue these to serialize independent jobs across cores.
  4. Maps `CPU_P#<N>` / `CPU_E#<N>` to a core name from a user-provided
     mapping (cpu_p_kind, cpu_e_kind), then to a registry entry whose
     harts pin the runtime worker. Default: cpu_p_kind=rvv, cpu_e_kind=scalar.
  5. Emits `<schedule>_dispatch_table.{h,c}` containing one entry per
     XPU-RT dispatch, ordered by start_time. The runtime walks this
     table to drive execution.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from dataclasses import dataclass
from typing import Optional

from modelblaster.pipeline import core_registry


HEADER = "/* @generated by modelblaster/pipeline/ingest_xpurt_schedule.py — do not edit. */"


@dataclass
class XpurtEntry:
    entry_id: int               # 0..N-1 (table position after sort)
    schedule_key: str           # original JSON key, e.g. "mlp_control3_dispatch_0"
    job_name: str               # e.g. "mlp_control3"
    network: str                # e.g. "mlp_control" (instance suffix stripped)
    instance: int               # 0 for unique networks; 0..K-1 for periodic
    dispatch_id: int            # IR-side dispatch_id within `network`
    op: str                     # echo from IR (linear, conv2d, ...)
    name: str                   # echo from IR (e.g. "mlp.0")
    core_name: str              # registry core name (e.g. "rvv0" or "rocket0")
    core_kind: str              # registry kind (e.g. "rvv", "scalar")
    hart: int                   # preferred hart (from registry); -1 if unbound
    start_time_ms: float
    duration_ms: float
    deps_entry_ids: tuple[int, ...]   # in-table entry_ids of intra-job deps
    time_dep_entry_id: int            # cross-job edge, -1 if none


# ---------- parsing helpers --------------------------------------------------

_INSTANCE_RE = re.compile(r"^(?P<base>.+?)(?P<idx>\d+)$")


def _split_job_name(job: str) -> tuple[str, int]:
    """Split a job_name like "mlp_control3" into ("mlp_control", 3); a name
    without a trailing instance index returns (job, 0)."""
    m = _INSTANCE_RE.match(job)
    if not m:
        return job, 0
    base = m.group("base")
    idx = int(m.group("idx"))
    return base, idx


def _resolve_target(core_label: str,
                    cpu_p_kind: str, cpu_e_kind: str,
                    reg: core_registry.CoreRegistry) -> tuple[str, str, int]:
    """Resolve "CPU_P#<n>" / "CPU_E#<n>" to a registry (name, kind, hart).

    XPU-RT works in abstract machine slots (CPU_P#0, CPU_E#0). The user
    tells us which kind in the registry corresponds to each slot
    (e.g. CPU_P -> rvv, CPU_E -> scalar). We then pick the n-th core of
    that kind.
    """
    label, _, idx_str = core_label.partition("#")
    idx = int(idx_str) if idx_str else 0
    if label.upper() == "CPU_P":
        kind = cpu_p_kind
    elif label.upper() == "CPU_E":
        kind = cpu_e_kind
    else:
        raise ValueError(f"unknown machine label {core_label!r}; "
                         f"expected CPU_P#<n> or CPU_E#<n>")
    candidates = reg.by_kind.get(kind, ())
    if not candidates:
        raise ValueError(
            f"registry {reg.system!r} has no cores of kind {kind!r} "
            f"(needed by {core_label}); add one or remap with "
            f"--cpu-p-kind/--cpu-e-kind")
    if idx >= len(candidates):
        raise ValueError(
            f"{core_label} indexes core #{idx} but registry only has "
            f"{len(candidates)} cores of kind {kind!r}")
    c = candidates[idx]
    hart = c.harts[0] if c.harts else -1
    return c.name, c.kind, hart


def load(schedule_path: str,
         irs_by_network: dict[str, dict],
         reg: core_registry.CoreRegistry,
         *,
         cpu_p_kind: str = "rvv",
         cpu_e_kind: str = "scalar") -> list[XpurtEntry]:
    """Parse, validate, and order an XPU-RT schedule. Returns entries
    sorted by start_time, with cross-references resolved to entry_ids."""
    with open(schedule_path) as f:
        doc = json.load(f)
    raw = doc.get("dispatches")
    if not isinstance(raw, dict) or not raw:
        raise ValueError(f"{schedule_path}: 'dispatches' missing or empty")

    # Build dispatch_id index per network IR + remap from IR-space
    # dispatch_id to codegen-space dispatch table index.
    #
    # `generate_skeleton.py` filters out zero-cost IR ops (view,
    # chunk2_c1) — they're aliasing-only and produce no kernel call.
    # The dispatch table `MODEL_<UMID>_DISPATCH_FNS_<BS>[]` is built by
    # appending fns for each non-zero-cost op IN IR ORDER, so the table
    # is sized OP_COUNT == n(non-zero-cost) and indexed sequentially —
    # NOT by IR dispatch_id.
    #
    # If we passed the IR dispatch_id straight to the runtime, the
    # walker would call `MODEL_<UMID>_DISPATCH_FNS_<BS>[ir_did]` which
    # for ir_did >= n(non-zero-cost) reads past the end of the table
    # into adjacent static data and jalrs garbage. We saw exactly this
    # crash (mepc=garbage int8 weight bytes) on yolov8_nano which has 8
    # chunk2_c1 ops, so codegen produced a 204-entry table but
    # ir_dids ran 0..211.
    #
    # Fix: remap each schedule entry's IR-space dispatch_id to its
    # codegen index here. Zero-cost ops get codegen_idx=-1 — runtime
    # skips them but still posts the completion sem so dependents
    # unblock.
    _ZERO_COST_OPS = {"view", "chunk2_c1"}
    network_dispatches: dict[str, set[int]] = {}
    network_op_by_did: dict[str, dict[int, dict]] = {}
    network_remap: dict[str, dict[int, int]] = {}  # ir_did -> codegen_idx (-1 = zero-cost skip)
    for net, ir in irs_by_network.items():
        idx: dict[int, dict] = {}
        remap: dict[int, int] = {}
        codegen_idx = 0
        for op in ir.get("ops", []):
            d = op.get("dispatch_id")
            if d is None:
                continue
            idx[d] = op
            if op.get("op") in _ZERO_COST_OPS:
                remap[d] = -1
            else:
                remap[d] = codegen_idx
                codegen_idx += 1
        network_dispatches[net] = set(idx)
        network_op_by_did[net] = idx
        network_remap[net] = remap

    # In-table order: priority topological sort, where the priority
    # key is start_time. Pure start_time-then-alphabetical sort breaks
    # down for zero-cost ops — the scheduler legitimately gives a
    # zero-cost dep and its dependent the SAME start_time (dep ends
    # the instant it starts, dependent's earliest_start = dep's end =
    # dep's start). The tie was being broken by `k` lexicographically,
    # which ranks "...dispatch_10" < "...dispatch_9" and put the
    # dependent before its dep. Kahn's-algorithm-with-heap respects
    # deps always (a dependent only becomes "runnable" after every dep
    # has been emitted) while still emitting in start_time order
    # whenever the priority queue has multiple runnable entries.
    import heapq
    from collections import defaultdict
    adj: dict[str, list[str]] = defaultdict(list)
    indeg: dict[str, int] = {k: 0 for k in raw}
    for k, d in raw.items():
        # Both data deps and time_dep are ordering edges and must
        # appear before this entry in the table walk.
        edges = list(d.get("dependencies", []) or [])
        time_dep_key = d.get("time_dependency")
        if time_dep_key:
            edges.append(time_dep_key)
        for dep in edges:
            if dep not in raw:
                # Will be flagged later when we resolve to entry_ids;
                # don't bookkeep an edge to a non-existent node here.
                continue
            adj[dep].append(k)
            indeg[k] += 1

    heap: list[tuple[float, str]] = []
    for k, n in indeg.items():
        if n == 0:
            heapq.heappush(heap, (float(raw[k].get("start_time", 0.0) or 0.0), k))
    sorted_keys: list[str] = []
    while heap:
        _, k = heapq.heappop(heap)
        sorted_keys.append(k)
        for nxt in adj[k]:
            indeg[nxt] -= 1
            if indeg[nxt] == 0:
                heapq.heappush(heap,
                               (float(raw[nxt].get("start_time", 0.0) or 0.0), nxt))
    if len(sorted_keys) != len(raw):
        # Indicates a cycle in the schedule's dep graph — an XPU-RT bug.
        unscheduled = [k for k in raw if k not in sorted_keys]
        raise ValueError(
            f"schedule dep graph has a cycle — could not topologically "
            f"order all {len(raw)} entries (only {len(sorted_keys)} placed). "
            f"Stuck entries (first 10): {unscheduled[:10]}"
        )
    key_to_entry_id = {k: i for i, k in enumerate(sorted_keys)}

    entries: list[XpurtEntry] = []
    for entry_id, key in enumerate(sorted_keys):
        d = raw[key]
        job = d["job_name"]
        network, instance = _split_job_name(job)
        if network not in irs_by_network:
            raise ValueError(
                f"schedule entry {key!r} references unknown network {network!r}; "
                f"known: {sorted(irs_by_network)}")
        did = int(d["id"])
        if did not in network_dispatches[network]:
            raise ValueError(
                f"schedule entry {key!r}: dispatch_id={did} not in "
                f"network {network!r} (IR has {sorted(network_dispatches[network])[:8]}...)")
        op_record = network_op_by_did[network][did]

        core_name, core_kind, hart = _resolve_target(
            d["hardware_target"], cpu_p_kind, cpu_e_kind, reg)

        # Resolve deps (intra-job data deps) + time_dep (cross-job edge)
        # to in-table entry_ids. The walker's deadlock-freedom argument
        # (see modelblaster/notes/xpurt_walker_semantics.md §4.6) requires every
        # edge to point STRICTLY BACKWARD in entry_id order — i.e. only at
        # entries that have already been walked past, regardless of which
        # kind owns them. The table is start_time-sorted, so XPU-RT can
        # only legitimately produce backward edges anyway; assert it
        # explicitly here so an out-of-spec scheduler emission fails at
        # ingest instead of deadlocking the harness mid-walk.
        deps_ids: list[int] = []
        for dep_key in d.get("dependencies", []) or []:
            if dep_key not in key_to_entry_id:
                raise ValueError(
                    f"{key!r} depends on unknown entry {dep_key!r}")
            dep_id = key_to_entry_id[dep_key]
            if dep_id >= entry_id:
                raise ValueError(
                    f"{key!r} (entry_id={entry_id}) has FORWARD dep "
                    f"{dep_key!r} (entry_id={dep_id}); deps must point "
                    f"backward in start_time order. Likely a scheduler "
                    f"bug — XPU-RT should not emit forward edges.")
            deps_ids.append(dep_id)
        time_dep_id = -1
        time_dep_key = d.get("time_dependency")
        if time_dep_key:
            if time_dep_key not in key_to_entry_id:
                raise ValueError(
                    f"{key!r} time_dependency points at unknown {time_dep_key!r}")
            time_dep_id = key_to_entry_id[time_dep_key]
            if time_dep_id >= entry_id:
                raise ValueError(
                    f"{key!r} (entry_id={entry_id}) has FORWARD time_dep "
                    f"{time_dep_key!r} (entry_id={time_dep_id}); "
                    f"time_dep must point backward in start_time order.")

        codegen_did = network_remap[network][did]
        entries.append(XpurtEntry(
            entry_id=entry_id,
            schedule_key=key,
            job_name=job,
            network=network,
            instance=instance,
            # codegen-space index, matches MODEL_<UMID>_DISPATCH_FNS_<BS>[]
            # layout. -1 means "zero-cost op, runtime should skip the
            # dispatch fn call but still post the completion sem".
            dispatch_id=codegen_did,
            op=op_record["op"],
            name=op_record.get("name", f"dispatch_{did}"),
            core_name=core_name,
            core_kind=core_kind,
            hart=hart,
            start_time_ms=float(d.get("start_time", 0.0) or 0.0),
            duration_ms=float(d.get("duration", 0.0) or 0.0),
            deps_entry_ids=tuple(deps_ids),
            time_dep_entry_id=time_dep_id,
        ))
    return entries


# ---------- C-table emission --------------------------------------------------


def emit_table(entries: list[XpurtEntry], out_path: str,
               schedule_name: str) -> None:
    """Emit one .c file containing the schedule table. The header comes
    next to it as <out_path>.h."""
    h_path = out_path[:-2] + ".h" if out_path.endswith(".c") else out_path + ".h"

    upper = schedule_name.replace(".", "_").replace("-", "_").upper()

    # Build per-entry deps arrays + interned strings.
    deps_arrays: list[str] = []
    for e in entries:
        if e.deps_entry_ids:
            arr = ", ".join(str(d) for d in e.deps_entry_ids)
            deps_arrays.append(
                f"static const int sched_{e.entry_id}_deps[] = {{ {arr} }};"
            )

    rows: list[str] = []
    for e in entries:
        n_deps = len(e.deps_entry_ids)
        deps_ref = (f"sched_{e.entry_id}_deps" if n_deps else "NULL")
        rows.append(
            f'    {{ .entry_id = {e.entry_id}, '
            f'.network = "{e.network}", .instance = {e.instance}, '
            f'.dispatch_id = {e.dispatch_id}, '
            f'.job_name = "{e.job_name}", '
            f'.op = "{e.op}", .name = "{e.name}", '
            f'.core_name = "{e.core_name}", .core_kind = "{e.core_kind}", '
            f'.hart = {e.hart}, '
            f'.start_time_ms = {e.start_time_ms!r}f, '
            f'.duration_ms = {e.duration_ms!r}f, '
            f'.n_deps = {n_deps}, .deps = {deps_ref}, '
            f'.time_dep_entry_id = {e.time_dep_entry_id} }},'
        )

    h = f"""{HEADER}
#pragma once

#include <stddef.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* One entry per XPU-RT-scheduled dispatch, sorted by start_time.
 * The runtime walks this table; entries' .deps[] / .time_dep_entry_id
 * are in-table indices used to enforce cross-dispatch ordering. */
typedef struct {{
    int            entry_id;
    const char    *network;        /* IR network name, e.g. "mlp_control" */
    int            instance;       /* 0..K-1 across multiple instances of the same network */
    int            dispatch_id;    /* IR dispatch_id within `network` */
    const char    *job_name;       /* XPU-RT job_name, e.g. "mlp_control3" */
    const char    *op;             /* IR op kind (e.g. "linear") */
    const char    *name;           /* IR node name (e.g. "mlp.0") */
    const char    *core_name;      /* registry core name (rocket0/rvv0/...) */
    const char    *core_kind;      /* registry kind (scalar/rvv/gemmini/...) */
    int            hart;           /* preferred hart, -1 if unbound */
    float          start_time_ms;  /* XPU-RT-issued start time (ms) */
    float          duration_ms;    /* XPU-RT-modeled duration (ms) */
    int            n_deps;
    const int     *deps;           /* in-table entry_ids of intra-job data deps */
    int            time_dep_entry_id; /* cross-job ordering edge, -1 if none */
}} xpurt_sched_entry_t;

#define {upper}_N_ENTRIES   {len(entries)}

extern const xpurt_sched_entry_t {upper}_TABLE[{upper}_N_ENTRIES];

#ifdef __cplusplus
}}
#endif
"""

    c = f"""{HEADER}
#include <stddef.h>
#include "{os.path.basename(h_path)}"

{chr(10).join(deps_arrays) if deps_arrays else "/* (no entries with deps) */"}

const xpurt_sched_entry_t {upper}_TABLE[{upper}_N_ENTRIES] = {{
{chr(10).join(rows)}
}};
"""

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(h_path, "w") as f:
        f.write(h)
    with open(out_path, "w") as f:
        f.write(c)


# ---------- CLI ---------------------------------------------------------------


def _main() -> None:
    ap = argparse.ArgumentParser(
        description="Ingest an XPU-RT schedule.json into a C dispatch table.")
    ap.add_argument("--schedule", required=True,
                    help="path to scheduled_*.json emitted by run_xpurt_schedule.py")
    ap.add_argument("--registry", required=True,
                    help="path to an modelblaster/cores/*.json")
    ap.add_argument("--ir", action="append", required=True,
                    help="<network>:<graph.json> — repeat once per network "
                         "referenced by the schedule")
    ap.add_argument("--out", required=True,
                    help="path to write the .c (companion .h is auto-derived)")
    ap.add_argument("--cpu-p-kind", default="rvv",
                    help="registry kind that CPU_P slots map to (default: rvv)")
    ap.add_argument("--cpu-e-kind", default="scalar",
                    help="registry kind that CPU_E slots map to (default: scalar)")
    ap.add_argument("--name", default=None,
                    help="schedule name (used for #define prefix); "
                         "defaults to the basename of --out without extension")
    args = ap.parse_args()

    irs: dict[str, dict] = {}
    for spec in args.ir:
        if ":" not in spec:
            raise SystemExit(f"--ir entry must be <network>:<graph.json>, got {spec!r}")
        net, path = spec.split(":", 1)
        irs[net] = json.load(open(path))

    reg = core_registry.load(args.registry)
    entries = load(args.schedule, irs, reg,
                   cpu_p_kind=args.cpu_p_kind,
                   cpu_e_kind=args.cpu_e_kind)

    schedule_name = args.name or os.path.splitext(os.path.basename(args.out))[0]
    emit_table(entries, args.out, schedule_name)
    print(f"ingested {len(entries)} entries from {args.schedule}")
    print(f"wrote {args.out}")
    print(f"wrote {args.out[:-2]}.h" if args.out.endswith(".c") else args.out + ".h")
    # Quick stats.
    by_kind: dict[str, int] = {}
    for e in entries:
        by_kind[e.core_kind] = by_kind.get(e.core_kind, 0) + 1
    print(f"by core kind: {dict(sorted(by_kind.items()))}")
    by_net: dict[str, int] = {}
    for e in entries:
        by_net[e.job_name] = by_net.get(e.job_name, 0) + 1
    print(f"by job_name: {by_net}")


if __name__ == "__main__":
    _main()
