CONFIG_SENSOR=y
CONFIG_BMI08X=y
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_STDOUT_CONSOLE=y

# ST VL53L0X support (enables vendor STLIB + driver)
CONFIG_VL53L0X=y
CONFIG_VL53L0X_PROXIMITY_THRESHOLD=100

CONFIG_CBPRINTF_FP_SUPPORT=y

# Debugging (so we can see why init fails)
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_SENSOR_LOG_LEVEL_DBG=y

