# RoSE co-sim: bridge driver + protocol + the multizone ToF virtual driver (bound by
# boards/spike_riscv64.overlay).
CONFIG_ROSE=y
CONFIG_ROSE_PROTOCOL=y
CONFIG_ROSE_SENSOR_TOF_ZONE=y

CONFIG_PICOLIBC=y
CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_FPU=y
