CONFIG_I2C=y
CONFIG_SENSOR=y

# VL53L5CX multizone ToF driver (new)
CONFIG_VL53L5CX=y
CONFIG_VL53L5CX_LPN=n

# Optional: make prints of floats possible if you add them later
CONFIG_PICOLIBC_IO_FLOAT=y