"""Emit kernels.h + kernels.c for a model IR.

Two orthogonal axes:

  --backend reference|llm           where do kernel implementations come from
  --target  scalar|rvv|...          which HW backend they target

Backends are declared in agents/pipeline/backends.py. Each carries its own
optimization guide (used in correctness AND optimize prompts), prj.conf
overlay, kernel-only compile flags, spike --isa args, and verify routing
(host_ctypes for natively-runnable code, spike_harness for code that needs
to be cross-compiled and exercised on spike).

Optimize phase (--optimize) runs a beam search over LLM-proposed faster
equivalents, gated by per-op cycle measurement on spike with the right
backend args. Tunable via --beam, --expansions, --iterations.
"""

from __future__ import annotations

import argparse
import json
import os
from typing import Optional

from agents.pipeline import backends as backends_mod
from agents.pipeline.backends import (
    Backend, VERIFY_HOST_CTYPES, VERIFY_SPIKE_HARNESS,
)
from agents.pipeline.bedrock_client import BedrockClient, extract_code_block
from agents.pipeline.reference_kernels import (
    KERNEL_SPECS, KernelSpec, shapes_from_ir,
)
from agents.pipeline.verify_kernel import verify as host_verify, VerifyResult


HEADER = "/* @generated by agents/pipeline/generate_kernels.py — do not edit. */"

PROMPTS_DIR = os.path.join(os.path.dirname(__file__), "prompts")


# ---------------------------------------------------------------------------
# Prompt scaffolding (shared by correctness + optimize phases)
# ---------------------------------------------------------------------------

def _load_backend_guide(backend: Backend) -> str:
    path = os.path.join(PROMPTS_DIR, backend.optimization_guide)
    with open(path) as f:
        return f.read()


def _correctness_system_prompt(backend: Backend, guide: str) -> str:
    return f"""\
You are a senior C99 programmer specializing in correct numerical kernels for
embedded RISC-V (rv64imafdc) running under Zephyr, targeting the **{backend.name}**
HW backend ({backend.description}). Your output is compiled with -O2,
linked into a Zephyr application, run on a spike RISC-V simulator, and
validated against a reference implementation at multiple shapes
(atol=1e-4, rtol=1e-3).

The guide below tells you what code style and intrinsics are acceptable for
this target. Follow it.

----- BEGIN TARGET GUIDE -----
{guide}
----- END TARGET GUIDE -----

Strict output rules:
- Reply with exactly ONE ```c fenced code block.
- The block contains exactly the requested function definition. No extras.
- Do NOT include any headers (no `#include`). The build system already
  prepends `<stddef.h>`, `<float.h>`, `<stdint.h>`, `<math.h>` for every
  backend, plus any target-specific headers (e.g. `<riscv_vector.h>` for
  the rvv target). `size_t`, `FLT_MAX`, fixed-width int types, `expf`,
  and target intrinsics are in scope without action on your part.
- Do NOT declare the function `static` or `inline`.
- Do NOT write a main(), helper functions, typedefs, macros, or globals.
- Use `float` (not double).
- Match the requested signature byte-for-byte (parameter names too).
"""


def _optimize_system_prompt(backend: Backend, guide: str) -> str:
    return f"""\
You are a senior C99 programmer specializing in fast numerical kernels for
embedded RISC-V (rv64imafdc) running under Zephyr, targeting the **{backend.name}**
HW backend ({backend.description}). You are given a working kernel and must
produce a faster equivalent for this target.

The optimized kernel will be:
- compiled with -O2 by riscv64-zephyr-elf-gcc
- linked into a Zephyr application and run on a spike RISC-V simulator
- profiled via rdcycle (mcycle CSR), reading the actual cycle count
- validated against a reference implementation at multiple shapes
  (atol=1e-4, rtol=1e-3)

If verification fails OR the new cycle count is not lower than the baseline,
your output is discarded. Aim for clear, correct, measurably faster code.

The guide below describes optimization techniques applicable to this target.
Stay within it.

----- BEGIN TARGET GUIDE -----
{guide}
----- END TARGET GUIDE -----

Strict output rules:
- Reply with exactly ONE ```c fenced code block.
- Output exactly the requested function definition. No extras.
- Do NOT include any headers (no `#include`). The build system already
  prepends `<stddef.h>`, `<float.h>`, `<stdint.h>`, `<math.h>` for every
  backend, plus any target-specific headers (e.g. `<riscv_vector.h>` for
  the rvv target). `size_t`, `FLT_MAX`, fixed-width int types, `expf`,
  and target intrinsics are in scope without action on your part.
- Do NOT declare the function `static` or `inline`.
- Do NOT write a main(), helper functions, typedefs, macros, or globals.
- Use `float` (not double).
- Match the requested signature byte-for-byte (parameter names too).
"""


def _correctness_user_prompt(spec: KernelSpec, shapes: list[dict],
                             algorithm) -> str:
    """Correctness prompt using a specific algorithm seed.

    `algorithm` is an AlgorithmCandidate from spec.algorithms — its
    description and reference_impl tell the LLM what *style* of
    implementation to produce. The verify oracle stays
    spec.reference_impl (algorithm-agnostic) so any equivalent kernel
    passes.
    """
    shapes_lines = "\n".join(f"  - {s}" for s in shapes)
    return f"""\
Implement this kernel:

    {spec.signature};

Semantics:
{spec.semantics}

You are implementing this op using the **{algorithm.name}** algorithm.

Algorithm description:
{algorithm.description}

Here is a correct implementation in this algorithmic style:

```c
{algorithm.reference_impl.rstrip()}
```

CRITICAL — preserve the algorithmic structure. Your job is NOT to substitute
a different, equivalent algorithm. If the reference allocates an
intermediate buffer and fills it before computing the output, your kernel
MUST also allocate and fill that buffer first (then compute). If the
reference has multiple sequential stages (e.g. gather, then matmul), your
kernel MUST keep them as separate stages — don't fuse them into a single
loop nest, even if that would produce equivalent output. The optimization
phase will allow restructuring; this correctness phase only allows
**within-stage** transforms (vectorizing a loop, swapping intrinsics, etc.).
Producing a different algorithm here, even if numerically correct, defeats
the purpose of the algorithm-database design.

Shapes your kernel will be tested at (it must be correct for all of these):
{shapes_lines}

This is the CORRECTNESS phase. Aim for the simplest, most obviously-correct
implementation in the {algorithm.name} algorithmic style that compiles and
matches the verify oracle numerically. There is a separate, later
optimization phase where you'll be asked to produce a faster equivalent.
Loop unrolling, multi-accumulator patterns, tiling, and similar transforms
belong in that later phase — they introduce tail-loop and indexing edge
cases that are easy to get wrong on the first pass. Get correct first.

Remember: ONE ```c block, only the function definition, no extras.
"""


def _retry_prompt(prev_code: str, diagnostic: str) -> str:
    return f"""\
Your previous attempt failed verification. The diagnostic was:

{diagnostic}

Your previous code:

```c
{prev_code}
```

Produce a corrected implementation. Same output rules: one ```c block, only
the function definition, no headers or extras.
"""


def _optimize_user_prompt(
    spec: KernelSpec, shapes: list[dict], baseline_code: str,
    baseline_cycles: int, parent_history: list[tuple[str, int]],
) -> str:
    shapes_lines = "\n".join(f"  - {s}" for s in shapes)
    history_block = ""
    if parent_history:
        history_block = "Earlier attempts you have already made (do not repeat them):\n\n"
        for i, (code, cyc) in enumerate(parent_history, 1):
            history_block += f"Attempt {i} ({cyc} cycles):\n```c\n{code.rstrip()}\n```\n\n"
    return f"""\
Optimize this kernel:

    {spec.signature};

Semantics:
{spec.semantics}

It must remain numerically equivalent to the reference at these test shapes:
{shapes_lines}

Current implementation ({baseline_cycles} cycles total across the model):

```c
{baseline_code.rstrip()}
```

{history_block}\
Produce a faster equivalent. Output the function definition only, in one
```c block.
"""


# ---------------------------------------------------------------------------
# File emit
# ---------------------------------------------------------------------------

def _kernel_mangled_name(op: str, model_name: Optional[str]) -> str:
    """Mangled kernel function name. Cache files stay unmangled (`kernel_op`)
    so they're reusable across models; mangling happens at emit time so two
    models' kernels.c can link side-by-side without collisions."""
    if model_name is None:
        return f"kernel_{op}"
    # _c_ident is in generate_skeleton; import lazily to avoid a hard dep loop.
    from agents.pipeline.generate_skeleton import _c_ident
    return f"kernel_{op}_{_c_ident(model_name)}"


def _mangle_kernel_in_text(text: str, op: str, model_name: Optional[str]) -> str:
    """Rename every `kernel_<op>` token to `kernel_<op>_<mid>` in `text`.

    Conservative: matches the bare identifier `kernel_<op>` followed by either
    `(` (call/definition site) or whitespace/`;`/`,` (declaration). Doesn't
    touch identifiers that just have `kernel_<op>` as a prefix
    (e.g. `kernel_linear_s8` is unchanged when op=`linear`).
    """
    if model_name is None:
        return text
    import re
    new_name = _kernel_mangled_name(op, model_name)
    pattern = re.compile(rf"\bkernel_{re.escape(op)}\b")
    return pattern.sub(new_name, text)


def emit_kernels_h(specs: list[KernelSpec], out_dir: str,
                   model_name: Optional[str] = None) -> None:
    lines = [HEADER, "#pragma once", "", '#ifdef __cplusplus',
             'extern "C" {', "#endif", ""]
    for spec in specs:
        sig = _mangle_kernel_in_text(spec.signature, spec.op, model_name)
        lines.append(f"{sig};")
    lines += ["", "#ifdef __cplusplus", "}", "#endif", ""]
    with open(os.path.join(out_dir, "kernels.h"), "w") as f:
        f.write("\n".join(lines))


_BASE_KERNEL_INCLUDES = ("<stddef.h>", "<float.h>", "<stdint.h>", "<math.h>")


def emit_kernels_c(
    impls: dict[str, str], source_label: str, out_dir: str,
    backend: Optional[Backend] = None,
    model_name: Optional[str] = None,
) -> None:
    parts = [HEADER, f"/* source: {source_label} */"]
    # Universal headers (FLT_MAX/INT64_MAX/size_t are kernel-friendly and free).
    for inc in _BASE_KERNEL_INCLUDES:
        parts.append(f"#include {inc}")
    if backend is not None:
        parts.append(f"/* target: {backend.name} */")
        for inc in backend.kernel_includes:
            parts.append(f"#include {inc}")
    parts += ['#include "kernels.h"', ""]
    for op in sorted(impls):
        body = _mangle_kernel_in_text(impls[op], op, model_name)
        parts.append(body.rstrip())
        parts.append("")
    with open(os.path.join(out_dir, "kernels.c"), "w") as f:
        f.write("\n".join(parts))


# ---------------------------------------------------------------------------
# Verify routing — backend dictates host_ctypes vs spike_harness
# ---------------------------------------------------------------------------

def _check_signature(candidate: str, spec: KernelSpec) -> Optional[str]:
    """Cheap lexical check that the candidate's first function definition
    matches the expected signature byte-for-byte (whitespace-insensitive,
    parameter names included). Catches LLM mistakes like reordering ints
    before we burn a Zephyr build / spike run on it.
    """
    cand_norm = " ".join(candidate.split())
    sig_norm = " ".join(spec.signature.split())
    if (
        cand_norm.startswith(sig_norm + " {")
        or cand_norm.startswith(sig_norm + "{")
    ):
        return None
    return (
        f"signature mismatch (parameter names/order must match the declaration "
        f"in kernels.h byte-for-byte).\n"
        f"  expected: {sig_norm}\n"
        f"  got:      {cand_norm[: len(sig_norm) + 16]}..."
    )


# Lexical structural checks per algorithm. Kept lightweight: a substring
# search for an identifier we expect to see if Llama actually followed the
# algorithmic structure. False negatives (different naming) drop into the
# slow verify path which still works; the goal is just to fail FAST when
# Llama is obviously not following the algorithm.
_ALGORITHM_REQUIRED_SUBSTRINGS: dict[str, tuple[str, ...]] = {
    # im2col_gemm: must allocate and populate the im2col buffer.
    "im2col_gemm": ("im2col_buf",),
    # oc_blocked: must have an outer OC tile loop. Looking for the
    # `oc_outer` identifier from the seed example is enough to catch the
    # most common LLM mistake (collapsing the outer-OC loop and writing
    # the direct algorithm under the cache-blocked label).
    "oc_blocked": ("oc_outer", "TILE_OC"),
}


def _check_algorithm_structure(candidate: str, algorithm_name: Optional[str]
                               ) -> Optional[str]:
    if algorithm_name is None:
        return None
    required = _ALGORITHM_REQUIRED_SUBSTRINGS.get(algorithm_name)
    if not required:
        return None
    cand_norm = candidate
    missing = [s for s in required if s not in cand_norm]
    if missing:
        return (
            f"algorithm '{algorithm_name}' structural check failed — "
            f"candidate is missing required identifier(s) {missing}. "
            f"This usually means the kernel fused the stages or "
            f"substituted a different algorithm. Re-read the algorithm "
            f"description and produce code that uses the named "
            f"intermediate buffer."
        )
    return None


def _verify(
    spec: KernelSpec, candidate: str, shapes: list[dict],
    *, backend: Backend,
    impls: Optional[dict[str, str]] = None,
    specs: Optional[list[KernelSpec]] = None,
    repo_root: Optional[str] = None,
    model_dir: Optional[str] = None,
    build_dir: Optional[str] = None,
    harness_dir: Optional[str] = None,
    io_path: Optional[str] = None,
    algorithm_name: Optional[str] = None,
) -> VerifyResult:
    sig_err = _check_signature(candidate, spec)
    if sig_err is not None:
        return VerifyResult(False, sig_err)
    struct_err = _check_algorithm_structure(candidate, algorithm_name)
    if struct_err is not None:
        return VerifyResult(False, struct_err)

    if backend.verify_method == VERIFY_HOST_CTYPES:
        return host_verify(spec, candidate, shapes)

    if backend.verify_method == VERIFY_SPIKE_HARNESS:
        # Build the full harness with this candidate substituted, run on
        # spike, and require the model output to match the PyTorch golden
        # within tolerance. This is necessarily coarser than per-shape
        # ctypes verify, but it's the only correctness check available for
        # backends with target-only intrinsics.
        if not all([impls is not None, specs is not None, repo_root,
                    model_dir, build_dir, harness_dir, io_path]):
            return VerifyResult(
                False,
                "spike-harness verify requires impls/specs/paths/io to be wired in",
            )
        from agents.pipeline.profile_kernel import build_and_run, ProfileError
        trial = dict(impls)  # type: ignore[arg-type]
        trial[spec.op] = candidate
        try:
            res = build_and_run(
                trial, specs,  # type: ignore[arg-type]
                backend=backend, model_dir=model_dir,  # type: ignore[arg-type]
                build_dir=build_dir,  # type: ignore[arg-type]
                repo_root=repo_root,  # type: ignore[arg-type]
                harness_dir=harness_dir,  # type: ignore[arg-type]
                pristine=False, io_path=io_path,
            )
        except ProfileError as e:
            return VerifyResult(False, f"spike-harness build/run failed:\n{e}")
        if res.golden_ok is False:
            # Decode where the divergence happened so the LLM has something
            # actionable to fix on retry.
            import numpy as _np
            golden = _np.load(io_path)["output"].astype(_np.float32).reshape(-1)  # type: ignore[arg-type]
            actual = res.output.astype(_np.float32) if res.output is not None else None
            extra = ""
            if actual is not None and actual.shape == golden.shape:
                abs_err = _np.abs(actual - golden)
                first = int(_np.argmax(abs_err > 0.0))
                ws = max(0, first - 2)
                we = min(len(golden), first + 6)
                extra = (
                    f"\n  first divergence at output flat_idx={first}\n"
                    f"  output[{ws}:{we}] expected: "
                    f"{[round(float(v), 6) for v in golden[ws:we]]}\n"
                    f"  output[{ws}:{we}] got:      "
                    f"{[round(float(v), 6) for v in actual[ws:we]]}"
                )
            return VerifyResult(
                False,
                f"model output diverged from golden (max_abs_err="
                f"{res.golden_max_abs_err:.3g}, max_rel_err="
                f"{res.golden_max_rel_err:.3g}){extra}",
                max_abs_err=res.golden_max_abs_err,
                max_rel_err=res.golden_max_rel_err,
            )
        return VerifyResult(
            True,
            f"spike-harness ok (max_abs_err={res.golden_max_abs_err:.3g} "
            f"max_rel_err={res.golden_max_rel_err:.3g}, "
            f"cycles={res.cycles_by_op})",
            max_abs_err=res.golden_max_abs_err,
            max_rel_err=res.golden_max_rel_err,
            cycles_by_op=dict(res.cycles_by_op) if res.cycles_by_op else None,
        )

    return VerifyResult(False, f"unknown verify_method {backend.verify_method}")


# ---------------------------------------------------------------------------
# Correctness loop
# ---------------------------------------------------------------------------

def _generate_one_llm_for_algorithm(
    spec: KernelSpec,
    algorithm,  # AlgorithmCandidate
    shapes: list[dict],
    client: BedrockClient,
    backend: Backend,
    correctness_system: str,
    max_retries: int,
    log,
    *,
    impls: dict[str, str],
    specs: list[KernelSpec],
    repo_root: Optional[str],
    model_dir: Optional[str],
    build_dir: Optional[str],
    harness_dir: Optional[str],
    io_path: Optional[str],
    cache_dir: Optional[str] = None,
) -> Optional[str]:
    """Try to drive Bedrock to produce a kernel implementing `algorithm`
    for this spec. Returns C source on success, None on giving up.
    """
    # Cache hit: if we have a previously-verified kernel for this
    # (op, target, algorithm) triple, reverify it and skip the LLM if it
    # still passes. Cache key is per-algorithm so different algos don't
    # clobber each other.
    cache_path = (
        os.path.join(cache_dir, f"{backend.name}_{spec.op}_{algorithm.name}.c")
        if cache_dir else None
    )
    if cache_path and os.path.exists(cache_path):
        cached = open(cache_path).read()
        log(f"  [{spec.op}/{algorithm.name}] trying cached kernel from {cache_path}")
        vres = _verify(
            spec, cached, shapes, backend=backend,
            impls=impls, specs=specs,
            repo_root=repo_root, model_dir=model_dir,
            build_dir=build_dir, harness_dir=harness_dir, io_path=io_path,
            algorithm_name=algorithm.name,
        )
        if vres.ok:
            log(f"  [{spec.op}/{algorithm.name}] cache HIT — {vres.message}")
            return cached
        log(f"  [{spec.op}/{algorithm.name}] cache stale "
            f"({vres.message.splitlines()[0]}); regenerating")

    prev_code: Optional[str] = None
    prev_diag: Optional[str] = None
    for attempt in range(1, max_retries + 1):
        if prev_code is None:
            user = _correctness_user_prompt(spec, shapes, algorithm)
        else:
            user = _retry_prompt(prev_code, prev_diag or "(no diagnostic)")
        log(f"  [{spec.op}/{algorithm.name}] attempt {attempt}/{max_retries}: "
            f"calling {client.model_id}")
        temp = 0.0 if attempt == 1 else 0.3
        res = client.converse(user=user, system=correctness_system,
                              max_tokens=2048, temperature=temp)
        log(f"  [{spec.op}/{algorithm.name}] tokens "
            f"in={res.input_tokens} out={res.output_tokens} "
            f"stop={res.stop_reason}")
        candidate = extract_code_block(res.text, lang="c")
        vres = _verify(
            spec, candidate, shapes, backend=backend,
            impls=impls, specs=specs,
            repo_root=repo_root, model_dir=model_dir,
            build_dir=build_dir, harness_dir=harness_dir, io_path=io_path,
            algorithm_name=algorithm.name,
        )
        if vres.ok:
            log(f"  [{spec.op}/{algorithm.name}] verify PASS — {vres.message}")
            if cache_path:
                os.makedirs(os.path.dirname(cache_path), exist_ok=True)
                with open(cache_path, "w") as f:
                    f.write(candidate)
                log(f"  [{spec.op}/{algorithm.name}] cached -> {cache_path}")
            return candidate
        # Print the first line of the diagnostic on the verify-FAIL line,
        # then dump the full message at low verbosity. Knowing exactly
        # which compile error / golden mismatch fired is essential when
        # the LLM keeps regenerating the same broken pattern.
        first_line = vres.message.splitlines()[0] if vres.message.strip() \
            else "(no diagnostic returned)"
        log(f"  [{spec.op}/{algorithm.name}] verify FAIL — {first_line}")
        if vres.message.strip() and len(vres.message.splitlines()) > 1:
            for line in vres.message.splitlines()[1:]:
                log(f"      {line}")
        prev_code = candidate
        prev_diag = vres.message
    log(f"  [{spec.op}/{algorithm.name}] gave up after {max_retries} attempts")
    return None


def generate_one_llm(
    spec: KernelSpec,
    shapes: list[dict],
    client: BedrockClient,
    backend: Backend,
    correctness_system: str,
    max_retries: int,
    log,
    *,
    impls: dict[str, str],
    specs: list[KernelSpec],
    repo_root: Optional[str],
    model_dir: Optional[str],
    build_dir: Optional[str],
    harness_dir: Optional[str],
    io_path: Optional[str],
    cache_dir: Optional[str] = None,
    algorithm_filter: Optional[set[str]] = None,
) -> Optional[tuple[str, str]]:
    """Try each algorithm in spec.algorithms in order. First one that
    produces a passing kernel wins. Returns ``(code, algorithm_name)`` so
    callers can track which algorithm was selected (e.g. to write the
    optimized variant back to the right cache file).
    `algorithm_filter` (if set) restricts
    to a subset of algorithm names — but if NO algorithms on this spec
    match the filter (e.g. user asked for 'im2col_gemm' but `linear` only
    has 'direct'), fall back to the spec's full algorithm list rather than
    failing the run. The filter is best-thought-of as "prefer these where
    available", not "only these everywhere".
    """
    if algorithm_filter is None:
        candidates = list(spec.algorithms)
    else:
        candidates = [a for a in spec.algorithms if a.name in algorithm_filter]
        if not candidates:
            log(f"  [{spec.op}] filter {sorted(algorithm_filter)} matches "
                f"none of this op's algorithms "
                f"{[a.name for a in spec.algorithms]}; falling back to all")
            candidates = list(spec.algorithms)
    # Also drop algorithms whose target_affinity excludes this backend.
    candidates = [
        a for a in candidates
        if not a.target_affinity or backend.name in a.target_affinity
    ]
    if not candidates:
        log(f"  [{spec.op}] no algorithms remain after target_affinity "
            f"filter for target {backend.name}")
        return None
    log(f"  [{spec.op}] algorithm queue: "
        f"{[a.name for a in candidates]}")

    # First pass: probe the cache across ALL candidate algorithms and
    # pick the one whose cached kernel is fastest in the spike harness.
    # This avoids picking the lexically-first algorithm when a slower
    # one is cached but a faster alternative also is — e.g. when both
    # `direct` (slow) and `im2col_gemm` (fast) are cached for conv2d on
    # RVV, we want to use im2col_gemm. The probe is a harness build+run
    # per cache HIT, but builds are incremental so this is cheap once
    # warmed up.
    if cache_dir is not None:
        best_cached_code: Optional[str] = None
        best_cached_algo: Optional[str] = None
        best_cached_cycles: Optional[int] = None
        for algorithm in candidates:
            cache_path = os.path.join(
                cache_dir, f"{backend.name}_{spec.op}_{algorithm.name}.c")
            if not os.path.exists(cache_path):
                continue
            cached = open(cache_path).read()
            log(f"  [{spec.op}/{algorithm.name}] probing cached kernel")
            vres = _verify(
                spec, cached, shapes, backend=backend,
                impls=impls, specs=specs,
                repo_root=repo_root, model_dir=model_dir,
                build_dir=build_dir, harness_dir=harness_dir, io_path=io_path,
                algorithm_name=algorithm.name,
            )
            if not vres.ok:
                log(f"  [{spec.op}/{algorithm.name}] cache stale "
                    f"({vres.message.splitlines()[0]})")
                continue
            cyc = (vres.cycles_by_op or {}).get(spec.op)
            log(f"  [{spec.op}/{algorithm.name}] cache HIT — "
                f"{cyc if cyc is not None else '?'} cycles")
            if best_cached_cycles is None or (cyc is not None and cyc < best_cached_cycles):
                best_cached_code = cached
                best_cached_algo = algorithm.name
                best_cached_cycles = cyc
        if best_cached_code is not None:
            log(f"  [{spec.op}] using cached algorithm '{best_cached_algo}' "
                f"({best_cached_cycles} cycles, fastest of cached options)")
            return best_cached_code, best_cached_algo

    # No cache hits — generate for each algorithm in order, take the
    # first one that verifies. (This is the original behavior; it's
    # the correct shape when there's no prior cycle data to compare.)
    for algorithm in candidates:
        code = _generate_one_llm_for_algorithm(
            spec, algorithm, shapes, client, backend, correctness_system,
            max_retries, log,
            impls=impls, specs=specs,
            repo_root=repo_root, model_dir=model_dir,
            build_dir=build_dir, harness_dir=harness_dir, io_path=io_path,
            cache_dir=cache_dir,
        )
        if code is not None:
            log(f"  [{spec.op}] using algorithm '{algorithm.name}'")
            return code, algorithm.name
    log(f"  [{spec.op}] all {len(candidates)} algorithms exhausted")
    return None


def collect_shapes(ir: dict, op: str, spec: KernelSpec) -> list[dict]:
    return shapes_from_ir(ir, op) + spec.extra_shapes


# ---------------------------------------------------------------------------
# Beam-search optimize loop
# ---------------------------------------------------------------------------

def _normalize(code: str) -> str:
    return " ".join(code.split())


def beam_search_optimize(
    spec: KernelSpec,
    shapes: list[dict],
    baseline_code: str,
    baseline_cycles: int,
    *,
    impls: dict[str, str],
    specs: list[KernelSpec],
    backend: Backend,
    client: BedrockClient,
    optimize_system: str,
    repo_root: str,
    model_dir: str,
    build_dir: str,
    harness_dir: str,
    io_path: Optional[str],
    beam: int,
    expansions: int,
    iterations: int,
    log,
) -> tuple[str, int, list[dict], list[tuple[str, int]]]:
    """Returns (best_code, best_cycles, history, all_viable_proposals).

    `all_viable_proposals` is every distinct (code, spike_cycles) pair
    that survived build+verify across all iterations, sorted by
    cycles ascending. Used downstream by the firesim re-rank step
    to pick the top-K spike survivors and re-score them on real RTL.
    Note: the baseline is NOT in this list — callers should add it.
    """
    from agents.pipeline.profile_kernel import build_and_run, ProfileError

    Beam = list[tuple[str, int]]
    beam_set: Beam = [(baseline_code, baseline_cycles)]
    best_code, best_cycles = baseline_code, baseline_cycles
    seen: set[str] = {_normalize(baseline_code)}
    history: list[dict] = []
    # Cumulative list of every distinct candidate that built+verified
    # successfully (across all iterations). The firesim re-rank step
    # consumes the top-K of this list to score on real RTL.
    all_viable: list[tuple[str, int]] = []

    for it in range(1, iterations + 1):
        log(f"  [{spec.op}] iter {it}/{iterations}  beam=[{', '.join(str(c) for _, c in beam_set)}]  best={best_cycles}")
        proposals: Beam = []
        for parent_idx, (parent_code, parent_cycles) in enumerate(beam_set):
            for exp in range(1, expansions + 1):
                log(f"    parent {parent_idx} ({parent_cycles} cyc) exp {exp}/{expansions}: calling LLM")
                user = _optimize_user_prompt(
                    spec, shapes, parent_code, parent_cycles,
                    parent_history=[(c, cy) for c, cy in beam_set if c != parent_code],
                )
                res = client.converse(
                    user=user, system=optimize_system,
                    max_tokens=2048, temperature=0.5,
                )
                log(f"      tokens in={res.input_tokens} out={res.output_tokens}")
                candidate = extract_code_block(res.text, lang="c")
                key = _normalize(candidate)
                if key in seen:
                    log(f"      duplicate, skip")
                    continue
                seen.add(key)

                # Combined verify + profile in one harness build.
                trial = dict(impls)
                trial[spec.op] = candidate
                try:
                    hres = build_and_run(
                        trial, specs, backend=backend,
                        model_dir=model_dir, build_dir=build_dir,
                        repo_root=repo_root, harness_dir=harness_dir,
                        pristine=False, io_path=io_path,
                    )
                except ProfileError as e:
                    # Surface the actual gcc error / spike trace so the loop
                    # operator can spot patterns. Keep the first 3 non-empty
                    # lines — usually enough to see the diagnostic without
                    # drowning the log.
                    err_lines = [ln for ln in str(e).splitlines() if ln.strip()]
                    head = err_lines[:3]
                    log(f"      build/spike FAIL:")
                    for ln in head:
                        log(f"        {ln[:200]}")
                    history.append({
                        "iter": it, "parent_cycles": parent_cycles,
                        "result": "build_fail",
                        "diag": " | ".join(head)[:600],
                    })
                    continue

                if io_path and hres.golden_ok is False:
                    log(f"      verify FAIL: golden mismatch "
                        f"(max_abs_err={hres.golden_max_abs_err:.3g})")
                    history.append({
                        "iter": it, "parent_cycles": parent_cycles,
                        "result": "verify_fail",
                        "diag": f"golden mismatch ({hres.golden_max_abs_err:.3g})",
                    })
                    continue

                # On host-verifiable backends, also re-run host verify with the
                # numerical sweep — catches cases where the model shapes are
                # narrow but extra_shapes are not.
                if backend.verify_method == VERIFY_HOST_CTYPES:
                    vres = host_verify(spec, candidate, shapes)
                    if not vres.ok:
                        log(f"      host verify FAIL: {vres.message.splitlines()[0]}")
                        history.append({
                            "iter": it, "parent_cycles": parent_cycles,
                            "result": "verify_fail",
                            "diag": vres.message.splitlines()[0],
                        })
                        continue

                new_cycles = hres.cycles_by_op.get(spec.op, 0)
                log(f"      {parent_cycles} -> {new_cycles} cyc"
                    f" ({(parent_cycles-new_cycles)/parent_cycles*100:+.1f}%)")
                history.append({
                    "iter": it, "parent_cycles": parent_cycles,
                    "result": "ok", "cycles": new_cycles,
                })
                proposals.append((candidate, new_cycles))
                all_viable.append((candidate, new_cycles))
                if new_cycles < best_cycles:
                    best_code, best_cycles = candidate, new_cycles

        if not proposals:
            log(f"  [{spec.op}] no surviving proposals this iter, stopping")
            break

        beam_set = sorted(proposals, key=lambda x: x[1])[:beam]
        if beam_set[0][1] >= best_cycles and best_cycles < baseline_cycles:
            log(f"  [{spec.op}] no further improvement, stopping early")
            break

    log(f"  [{spec.op}] BEST: {baseline_cycles} -> {best_cycles} "
        f"({(baseline_cycles - best_cycles) / baseline_cycles * 100:+.1f}%)")
    # Sort viable proposals cheapest-spike first; dedupe identical
    # bodies that may have come up across iterations.
    viable_sorted: list[tuple[str, int]] = []
    seen_norm: set[str] = set()
    for code, cyc in sorted(all_viable, key=lambda x: x[1]):
        key = _normalize(code)
        if key in seen_norm:
            continue
        seen_norm.add(key)
        viable_sorted.append((code, cyc))
    return best_code, best_cycles, history, viable_sorted


# ---------------------------------------------------------------------------
# Top-level driver
# ---------------------------------------------------------------------------

def generate(
    ir_path: str,
    out_dir: str,
    backend_name: str,
    target_name: str,
    *,
    max_retries: int = 4,
    optimize: bool = False,
    beam: int = 2,
    expansions: int = 3,
    iterations: int = 2,
    repo_root: Optional[str] = None,
    build_dir: Optional[str] = None,
    harness_dir: str = "agents/harness",
    io_path: Optional[str] = None,
    cache_dir: Optional[str] = None,
    algorithm_filter: Optional[set[str]] = None,
    quant: str = "fp32",
    # Opt-in: after the spike beam search picks a best, re-rank the
    # top-K spike survivors on FireSim RTL. The cache slot is replaced
    # with the firesim-best only if the firesim cycles drop by >=
    # FiresimEvalConfig.replacement_threshold_pct vs. the baseline. Off
    # by default — it's expensive (1-3 min per candidate FPGA build+run).
    firesim_eval: bool = False,
    firesim_top_k: int = 3,
    # Opt-in: include the memory-hierarchy stanza in the optimize-phase
    # system prompt. Only useful when firesim_eval=True (otherwise the
    # spike scorer is blind to cache wins, so the LLM has no incentive
    # to produce them).
    cache_aware_prompt: bool = False,
    firesim_op_filter: Optional[set[str]] = None,
) -> None:
    os.makedirs(out_dir, exist_ok=True)
    with open(ir_path) as f:
        ir = json.load(f)

    # The IR records the quantization mode it was extracted under; reject
    # mismatches (e.g. running an int8 IR through the fp32 codegen) loudly.
    ir_quant = ir.get("quant", "fp32")
    if quant != ir_quant:
        raise SystemExit(
            f"quant mismatch: caller passed --quant={quant} but IR was "
            f"extracted with quant={ir_quant}. Re-extract the model with "
            f"the same quant flag, or pass --quant={ir_quant}."
        )
    if quant not in ("fp32", "int8"):
        raise SystemExit(
            f"quant={quant!r} not implemented in generate_kernels yet "
            f"(have: fp32, int8)."
        )

    target = backends_mod.get(target_name)

    # `view` ops (flatten / dropout in eval mode) compile to a buffer alias in
    # the skeleton and have no kernel — skip them here.
    op_kinds = sorted({op["op"] for op in ir["ops"] if op["op"] != "view"})
    for k in op_kinds:
        if k not in KERNEL_SPECS:
            raise SystemExit(f"unknown op kind in IR: {k}")
    specs = [KERNEL_SPECS[k] for k in op_kinds]

    log = lambda msg: print(msg, flush=True)
    impls: dict[str, str] = {}
    # Per-op tracking of which algorithm was selected during baseline gen.
    # Used by the optimize loop to write the optimized kernel back to the
    # right cache file (same key the baseline read from).
    chosen_algo: dict[str, str] = {}

    needs_harness_paths = (
        target.verify_method == VERIFY_SPIKE_HARNESS
        or optimize
    )
    if needs_harness_paths:
        if not (repo_root and build_dir and io_path):
            raise SystemExit(
                f"target={target.name} verify_method={target.verify_method}"
                f" or --optimize requires --repo-root, --build-dir, --io"
            )

    # Correctness phase.
    if backend_name == "reference":
        log(f"backend=reference  target={target.name}  ops={op_kinds}")
        for spec in specs:
            impls[spec.op] = spec.reference_impl
    elif backend_name == "llm":
        client = BedrockClient()
        guide = _load_backend_guide(target)
        correctness_system = _correctness_system_prompt(target, guide)
        log(f"backend=llm  target={target.name}  ops={op_kinds}  "
            f"model={client.model_id}")
        # Seed impls with reference so spike-harness verify has stand-ins
        # for ops not yet generated.
        for spec in specs:
            impls[spec.op] = spec.reference_impl
        # First pass: write reference + emit so the harness can build at all.
        emit_kernels_h(specs, out_dir, model_name=ir["name"])
        emit_kernels_c(impls, "seed", out_dir, backend=target, model_name=ir["name"])
        for spec in specs:
            shapes = collect_shapes(ir, spec.op, spec)
            log(f"  [{spec.op}] verify shapes={shapes}")
            result = generate_one_llm(
                spec, shapes, client, target, correctness_system,
                max_retries, log,
                impls=impls, specs=specs,
                repo_root=repo_root, model_dir=out_dir,
                build_dir=build_dir, harness_dir=harness_dir, io_path=io_path,
                cache_dir=cache_dir,
                algorithm_filter=algorithm_filter,
            )
            if result is None:
                raise SystemExit(
                    f"failed to generate kernel for op '{spec.op}' "
                    f"after {max_retries} attempts"
                )
            code, chosen = result
            impls[spec.op] = code
            chosen_algo[spec.op] = chosen
    else:
        raise SystemExit(f"unknown --backend: {backend_name}")

    emit_kernels_h(specs, out_dir, model_name=ir["name"])
    emit_kernels_c(impls, backend_name, out_dir, backend=target, model_name=ir["name"])
    print(f"wrote {os.path.join(out_dir, 'kernels.h')}")
    print(f"wrote {os.path.join(out_dir, 'kernels.c')}  "
          f"(source={backend_name} target={target.name})")

    if not optimize:
        return

    # Optimize phase.
    if backend_name != "llm":
        log("optimize: requires --backend llm; reference impls are not expanded.")
        return

    log("")
    log(f"optimize: beam={beam} expansions={expansions} iterations={iterations}")
    log(f"optimize: harness={harness_dir} build_dir={build_dir} target={target.name}")

    from agents.pipeline.profile_kernel import build_and_run, ProfileError

    log("optimize: baseline build + profile (pristine)")
    try:
        baseline = build_and_run(
            impls, specs, backend=target,
            model_dir=out_dir, build_dir=build_dir, repo_root=repo_root,  # type: ignore[arg-type]
            harness_dir=harness_dir, pristine=True, io_path=io_path,
        )
    except ProfileError as e:
        raise SystemExit(f"baseline profile failed:\n{e}")
    if io_path and baseline.golden_ok is False:
        raise SystemExit(
            f"baseline diverged from PyTorch golden "
            f"(max_abs_err={baseline.golden_max_abs_err:.3g}); refusing to optimize"
        )
    baseline_cycles_by_op = baseline.cycles_by_op
    log("optimize: baseline cycles per op kind: "
        + ", ".join(f"{k}={v}" for k, v in sorted(baseline_cycles_by_op.items())))

    guide = _load_backend_guide(target)
    optimize_system = _optimize_system_prompt(target, guide)
    # When firesim_eval is requested with cache_aware_prompt, splice the
    # memory-model stanza into the optimize prompt so the LLM has an
    # explicit incentive to produce cache-locality wins. Only does any
    # good when firesim is also scoring — without it spike still ranks.
    if cache_aware_prompt:
        from agents.optimize.firesim_eval import memory_model_stanza
        stanza = memory_model_stanza()
        optimize_system = optimize_system + "\n\n" + stanza
        log("optimize: prompt enriched with target memory-hierarchy stanza")
    client = BedrockClient()

    # Pre-instantiate the firesim evaluator (one per generate() call). It
    # reuses a separate chipyard build dir from the spike build_dir so
    # the spike beam can rebuild while a firesim run is in flight.
    firesim_evaluator = None
    if firesim_eval:
        from agents.optimize.firesim_eval import (
            FiresimEvaluator, FiresimEvalConfig,
        )
        firesim_build_dir = (build_dir or "") + "_firesim_eval"
        firesim_evaluator = FiresimEvaluator(
            backend=target, impls=impls, specs=specs,
            repo_root=repo_root, model_dir=out_dir,  # type: ignore[arg-type]
            firesim_build_dir=firesim_build_dir,
            harness_dir=harness_dir, io_path=io_path,  # type: ignore[arg-type]
            config=FiresimEvalConfig(),
            log=log,
        )
        log(f"optimize: firesim re-rank ENABLED "
            f"(top_k={firesim_top_k}, build_dir={firesim_build_dir})")

    optimize_summary: dict[str, dict] = {}
    for spec in specs:
        baseline_op = baseline_cycles_by_op.get(spec.op, 0)
        if baseline_op <= 0:
            log(f"  [{spec.op}] no baseline cycles, skipping")
            continue
        log(f"\noptimize [{spec.op}] baseline={baseline_op}")
        shapes = collect_shapes(ir, spec.op, spec)
        best_code, best_cycles, history, viable = beam_search_optimize(
            spec, shapes, impls[spec.op], baseline_op,
            impls=impls, specs=specs, backend=target, client=client,
            optimize_system=optimize_system,
            repo_root=repo_root,  # type: ignore[arg-type]
            model_dir=out_dir,
            build_dir=build_dir,  # type: ignore[arg-type]
            harness_dir=harness_dir, io_path=io_path,
            beam=beam, expansions=expansions, iterations=iterations,
            log=log,
        )

        # FireSim re-rank: take the spike top-K survivors + spike-best
        # baseline and re-score on real RTL. Whichever has the lowest
        # firesim cycles wins for cache promotion. The spike-best stays
        # in `impls` as the in-process working copy (we don't want to
        # let firesim regress correctness silently).
        firesim_history: list[dict] = []
        firesim_best_cycles: Optional[int] = None
        if firesim_evaluator is not None and viable:
            run_op = (
                firesim_op_filter is None
                or spec.op in firesim_op_filter
            )
            if not run_op:
                log(f"  [{spec.op}/firesim] skipped (not in op filter)")
            else:
                # Refresh the evaluator's impls so non-targeted ops use
                # the spike-best from this iteration (otherwise stale
                # reference impls ride along and skew the harness).
                trial_impls = dict(impls)
                trial_impls[spec.op] = best_code
                firesim_evaluator.impls = trial_impls
                from agents.optimize.firesim_eval import evaluate_top_k
                fbest_code, fbest_cycles, firesim_history = evaluate_top_k(
                    spec, viable,
                    evaluator=firesim_evaluator,
                    spike_baseline=(best_code, best_cycles),
                    log=log, k=firesim_top_k,
                )
                if fbest_code is not None and fbest_cycles is not None:
                    firesim_best_cycles = fbest_cycles
                    # Promote to in-process impls + cache only if the
                    # firesim winner differs from the spike baseline.
                    # Identity check is on the normalized code body.
                    if _normalize(fbest_code) != _normalize(best_code):
                        log(f"  [{spec.op}/firesim] promoting firesim-best "
                            f"({fbest_cycles} cyc) over spike-best")
                        best_code = fbest_code

        impls[spec.op] = best_code
        optimize_summary[spec.op] = {
            "baseline": baseline_op,
            "best": best_cycles,
            "improvement_pct": (baseline_op - best_cycles) / baseline_op * 100.0,
            "history": history,
            "firesim_history": firesim_history,
            "firesim_best_cycles": firesim_best_cycles,
        }
        # Persist the optimized kernel back to the same cache slot the
        # baseline read from so a subsequent OPTIMIZE=0 sweep finds the
        # already-improved code on cache HIT and reuses it. Only overwrite
        # when we actually found an improvement — preserves the
        # "baseline LLM" cached file otherwise.
        if cache_dir and best_cycles < baseline_op and spec.op in chosen_algo:
            os.makedirs(cache_dir, exist_ok=True)
            cache_path = os.path.join(
                cache_dir,
                f"{target.name}_{spec.op}_{chosen_algo[spec.op]}.c",
            )
            with open(cache_path, "w") as f:
                f.write(best_code)
            log(f"  [{spec.op}] cached optimized -> {cache_path}")

    emit_kernels_h(specs, out_dir, model_name=ir["name"])
    emit_kernels_c(impls, f"{backend_name}-optimized", out_dir, backend=target, model_name=ir["name"])
    print(f"\nwrote {os.path.join(out_dir, 'kernels.c')}  "
          f"(source={backend_name}-optimized target={target.name})")

    summary_path = os.path.join(out_dir, "optimize_summary.json")
    with open(summary_path, "w") as f:
        json.dump(optimize_summary, f, indent=2)
    log(f"wrote {summary_path}")
    log("")
    log("optimize summary:")
    for op, s in sorted(optimize_summary.items()):
        log(f"  {op}: {s['baseline']} -> {s['best']} ({s['improvement_pct']:+.1f}%)")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ir", required=True, help="graph.json")
    ap.add_argument("--out-dir", required=True,
                    help="output dir for kernels.{c,h} and skeleton C")
    ap.add_argument("--backend", choices=["reference", "llm"], default="reference",
                    help="source of kernel implementations")
    ap.add_argument("--target", default="scalar",
                    help=f"HW backend ({sorted(backends_mod.BACKENDS)})")
    ap.add_argument("--max-retries", type=int, default=4)
    ap.add_argument("--optimize", action="store_true")
    ap.add_argument("--beam", type=int, default=2)
    ap.add_argument("--expansions", type=int, default=3)
    ap.add_argument("--iterations", type=int, default=2)
    ap.add_argument("--repo-root", default=None)
    ap.add_argument("--build-dir", default=None)
    ap.add_argument("--harness-dir", default="agents/harness")
    ap.add_argument("--io", default=None,
                    help="io.npz with the PyTorch golden output (required for "
                         "spike-harness verify and --optimize)")
    ap.add_argument("--cache-dir", default=None,
                    help="reuse PASSing kernels from this dir across runs "
                         "(saves <target>_<op>_<algo>.c on success, "
                         "reverifies on hit)")
    ap.add_argument("--algorithms", default="all",
                    help=("comma-separated algorithm names to try (in order) "
                          "for each op, or 'all' (default) to try every "
                          "algorithm registered on each spec, or 'default' "
                          "to use only the first algorithm of each spec "
                          "(matches old single-seed behavior)"))
    ap.add_argument("--quant", default="fp32",
                    help="quantization mode (fp32 only for now). Must match "
                         "the IR's recorded quant or generate_kernels errors "
                         "out.")
    ap.add_argument("--firesim-eval", action="store_true",
                    help="opt-in: after the spike beam search, re-rank the "
                         "top-K spike survivors on FireSim RTL and promote "
                         "the firesim-best to cache. Expensive (1-3 min "
                         "FPGA build+run per candidate) but the only way "
                         "to capture cache-locality wins. Requires --io.")
    ap.add_argument("--firesim-top-k", type=int, default=3,
                    help="how many spike-best candidates to re-score on "
                         "firesim per op. Total firesim runs per op = K + 1 "
                         "(K survivors + the spike-baseline). Default 3.")
    ap.add_argument("--cache-aware-prompt", action="store_true",
                    help="splice the target's memory-hierarchy stanza into "
                         "the optimize-phase system prompt. Steers the LLM "
                         "toward cache-locality wins. Only useful with "
                         "--firesim-eval (otherwise the scorer is blind).")
    ap.add_argument("--firesim-ops", default=None,
                    help="comma-separated op kinds to firesim re-rank. "
                         "Useful when iterating on just conv2d / linear "
                         "without paying FPGA time on every elementwise op. "
                         "Default (unset) = all ops.")
    args = ap.parse_args()

    if args.algorithms == "all":
        algorithm_filter = None
    elif args.algorithms == "default":
        # Use only the first algorithm of each spec — restored single-seed
        # behavior for back-compat / debugging.
        first_names = {spec.algorithms[0].name for spec in KERNEL_SPECS.values()}
        algorithm_filter = first_names
    else:
        algorithm_filter = {n.strip() for n in args.algorithms.split(",") if n.strip()}

    firesim_op_filter = None
    if args.firesim_ops:
        firesim_op_filter = {
            n.strip() for n in args.firesim_ops.split(",") if n.strip()
        }

    generate(
        args.ir, args.out_dir, args.backend, args.target,
        max_retries=args.max_retries,
        optimize=args.optimize,
        beam=args.beam, expansions=args.expansions, iterations=args.iterations,
        repo_root=args.repo_root, build_dir=args.build_dir,
        harness_dir=args.harness_dir, io_path=args.io,
        cache_dir=args.cache_dir,
        algorithm_filter=algorithm_filter,
        quant=args.quant,
        firesim_eval=args.firesim_eval,
        firesim_top_k=args.firesim_top_k,
        cache_aware_prompt=args.cache_aware_prompt,
        firesim_op_filter=firesim_op_filter,
    )


if __name__ == "__main__":
    main()
