"""IR + weights + io -> driver/weight/test C files for the Zephyr harness.

Outputs (all marked @generated):
    model.h, model.c             driver: run_model(input, output)
    weights.h, weights.c         const float arrays for each weight
    test_io.h                    sample input + golden output for host compare

Kernels (kernels.h, kernels.c) are produced by a separate stage:
    agents/pipeline/generate_kernels.py
which has --backend reference (hardcoded reference impls) and
--backend llm (Bedrock-driven, host-verified per op). Splitting them keeps
this stage purely deterministic and lets the LLM kernel pass evolve
independently behind the stable kernel ABI.
"""

from __future__ import annotations

import argparse
import json
import os
from typing import Any

import numpy as np


HEADER = "/* @generated by agents/pipeline/generate_skeleton.py — do not edit. */"


def _c_ident(name: str) -> str:
    return name.replace(".", "_").replace("-", "_")


def _f32(x: float) -> str:
    """Format a float32 value as a C float literal (round-trip safe).

    Always emits a decimal point or exponent before the `f` suffix so the
    compiler reads it as a float (not an integer with an illegal suffix).
    """
    f = float(np.float32(x))
    if np.isnan(f):
        return "(0.0f/0.0f)"
    if np.isinf(f):
        return "(1.0f/0.0f)" if f > 0 else "(-1.0f/0.0f)"
    s = f"{f:.9g}"
    # `g` may print "0", "1", "-2" with no decimal/exponent — append ".0"
    # so the `f` suffix binds to a floating literal.
    if "." not in s and "e" not in s and "E" not in s and "n" not in s:
        s += ".0"
    return s + "f"


def _array_lines(arr: np.ndarray, per_line: int = 8) -> list[str]:
    flat = arr.astype(np.float32).reshape(-1)
    out: list[str] = []
    for i in range(0, len(flat), per_line):
        chunk = flat[i : i + per_line]
        out.append("    " + ", ".join(_f32(v) for v in chunk) + ",")
    return out


def _array_lines_int(arr: np.ndarray, per_line: int = 16) -> list[str]:
    """Format an integer array as lines of comma-separated decimal literals."""
    flat = arr.reshape(-1)
    out: list[str] = []
    for i in range(0, len(flat), per_line):
        chunk = flat[i : i + per_line]
        out.append("    " + ", ".join(str(int(v)) for v in chunk) + ",")
    return out


# Map our IR dtype tags to C scalar types (used everywhere — buffer decls,
# run_model signature, weights.h, test_io.h). _Float16 is the standard
# scalar half-precision type in C — gcc supports it natively when
# compiling with `-march=...zfh` for RISC-V (Dima's Aug-13 patch wires
# this up automatically when CONFIG_RISCV_ISA_EXT_ZFH=y).
_DTYPE_TO_C = {
    "f32": "float",
    "f16": "_Float16",
    "i8":  "int8_t",
    "i32": "int32_t",
    "i64": "int64_t",
}


def _dtype_to_c(dtype: str) -> str:
    if dtype not in _DTYPE_TO_C:
        raise NotImplementedError(f"unknown IR dtype: {dtype}")
    return _DTYPE_TO_C[dtype]


def _np_to_c_dtype(np_dtype) -> tuple[str, str]:
    """(c_type, ir_dtype_tag) for a numpy weight blob's dtype."""
    if np_dtype == np.float32:
        return "float", "f32"
    if np_dtype == np.float16:
        return "_Float16", "f16"
    if np_dtype == np.int8:
        return "int8_t", "i8"
    if np_dtype == np.int32:
        return "int32_t", "i32"
    if np_dtype == np.int64:
        return "int64_t", "i64"
    raise NotImplementedError(f"unsupported weight dtype: {np_dtype}")


def _prod(shape: list[int]) -> int:
    n = 1
    for s in shape:
        n *= int(s)
    return n


def _buf_name(mid: str, tensor: str) -> str:
    """Intermediate-buffer symbol name. Mangled with the model id so
    multiple models can have a `buf_x` and still link without collision
    when the buffers are emitted with external (non-static) linkage.
    External linkage is required by the heterogeneous (harness_xpurt)
    flow: each (model, backend) is its own OBJECT lib, so file-static
    buffers would give each backend its own private copy and cross-
    backend dispatches would read zeroed scratch. The buffers TU is
    compiled once per model (NOT per backend) and shared by all
    backends; same model.c source compiled per backend re-uses the
    single shared definition via `extern` declarations."""
    return f"buf_{mid}_{_c_ident(tensor)}"


# Ops the skeleton routes through a parallel_for wrapper. Wrappers are
# emitted as static inlines in model.c with two implementations selected
# by AGENTS_USE_POOL: dispatch onto agents_pool when defined; plain
# sequential call to the mangled kernel otherwise. When a build doesn't
# need threading (single-model harness), the no-op fallback keeps
# agents_pool.h out of model.c so the harness has no POSIX dep.
_PARALLELIZED_OPS = {"linear", "conv2d"}


_LINEAR_WRAPPER = """
/* ---- linear: split outer N (output features), M==1 only ----------------- */
typedef struct {{
    const float *in;
    const float *w;
    const float *b;
    float *out;
    int M;
    int K;
    int N_total;
    int chunks;
}} parallel_linear_ctx_t;

static void parallel_linear_fn(void *ctx_, size_t i) {{
    parallel_linear_ctx_t *c = (parallel_linear_ctx_t *)ctx_;
    int n_per = (c->N_total + c->chunks - 1) / c->chunks;
    int n0 = (int)i * n_per;
    int n1 = n0 + n_per;
    if (n1 > c->N_total) n1 = c->N_total;
    if (n0 >= n1) return;
    kernel_linear_{mid}(c->in,
                        c->w + (size_t)n0 * (size_t)c->K,
                        c->b ? c->b + n0 : NULL,
                        c->out + n0,
                        c->M, c->K, n1 - n0);
}}

static inline void parallel_linear(void *pool_,
                                   const float *in, const float *w,
                                   const float *b, float *out,
                                   int M, int K, int N) {{
#ifdef AGENTS_USE_POOL
    /* agents_pool path: opaque agents_pool_t cast via void *. The
     * historical pthreadpool path was retired in Phase 4 of the
     * pthreadpool->agents_pool migration. */
    agents_pool_t pool = (agents_pool_t)pool_;
    if (pool == NULL || M != 1) {{
        kernel_linear_{mid}(in, w, b, out, M, K, N);
        return;
    }}
    size_t T = agents_pool_get_threads_count(pool);
    if (T <= 1 || (size_t)N < T) {{
        kernel_linear_{mid}(in, w, b, out, M, K, N);
        return;
    }}
    parallel_linear_ctx_t ctx = {{
        .in = in, .w = w, .b = b, .out = out,
        .M = M, .K = K, .N_total = N, .chunks = (int)T,
    }};
    agents_pool_parallelize_1d(pool, parallel_linear_fn, &ctx, T, 0);
#else
    (void)pool_;
    kernel_linear_{mid}(in, w, b, out, M, K, N);
#endif
}}
"""

_CONV2D_WRAPPER = """
/* ---- conv2d: split outer OC (output channels), N==1 only ---------------- */
typedef struct {{
    const float *in;
    const float *w;
    const float *b;
    float *out;
    int N;
    int IC;
    int IH;
    int IW;
    int OC_total;
    int KH;
    int KW;
    int SH;
    int SW;
    int PH;
    int PW;
    int OH;
    int OW;
    int chunks;
}} parallel_conv2d_ctx_t;

static void parallel_conv2d_fn(void *ctx_, size_t i) {{
    parallel_conv2d_ctx_t *c = (parallel_conv2d_ctx_t *)ctx_;
    int oc_per = (c->OC_total + c->chunks - 1) / c->chunks;
    int oc0 = (int)i * oc_per;
    int oc1 = oc0 + oc_per;
    if (oc1 > c->OC_total) oc1 = c->OC_total;
    if (oc0 >= oc1) return;
    size_t per_filter = (size_t)c->IC * (size_t)c->KH * (size_t)c->KW;
    size_t per_oc_out = (size_t)c->OH * (size_t)c->OW;
    kernel_conv2d_{mid}(c->in,
                        c->w + (size_t)oc0 * per_filter,
                        c->b ? c->b + oc0 : NULL,
                        c->out + (size_t)oc0 * per_oc_out,
                        c->N, c->IC, c->IH, c->IW,
                        oc1 - oc0, c->KH, c->KW,
                        c->SH, c->SW, c->PH, c->PW);
}}

static inline void parallel_conv2d(void *pool_,
                                   const float *in, const float *w,
                                   const float *b, float *out,
                                   int N, int IC, int IH, int IW,
                                   int OC, int KH, int KW,
                                   int SH, int SW, int PH, int PW) {{
#ifdef AGENTS_USE_POOL
    agents_pool_t pool = (agents_pool_t)pool_;
    if (pool == NULL || N != 1) {{
        kernel_conv2d_{mid}(in, w, b, out, N, IC, IH, IW,
                            OC, KH, KW, SH, SW, PH, PW);
        return;
    }}
    size_t T = agents_pool_get_threads_count(pool);
    if (T <= 1 || (size_t)OC < T) {{
        kernel_conv2d_{mid}(in, w, b, out, N, IC, IH, IW,
                            OC, KH, KW, SH, SW, PH, PW);
        return;
    }}
    int OH = (IH + 2 * PH - KH) / SH + 1;
    int OW = (IW + 2 * PW - KW) / SW + 1;
    parallel_conv2d_ctx_t ctx = {{
        .in = in, .w = w, .b = b, .out = out,
        .N = N, .IC = IC, .IH = IH, .IW = IW,
        .OC_total = OC, .KH = KH, .KW = KW,
        .SH = SH, .SW = SW, .PH = PH, .PW = PW,
        .OH = OH, .OW = OW, .chunks = (int)T,
    }};
    agents_pool_parallelize_1d(pool, parallel_conv2d_fn, &ctx, T, 0);
#else
    (void)pool_;
    kernel_conv2d_{mid}(in, w, b, out, N, IC, IH, IW,
                        OC, KH, KW, SH, SW, PH, PW);
#endif
}}
"""

_PARALLEL_WRAPPER_TEMPLATES = {
    "linear": _LINEAR_WRAPPER,
    "conv2d": _CONV2D_WRAPPER,
}


def _emit_parallel_wrappers(mid: str, used_ops: set[str]) -> str:
    """Emit static parallel_for wrappers ONLY for ops the model actually uses.
    Emitting for every parallelizable op leaks `kernel_<op>_<mid>` references
    that the kernels.c doesn't define when the model has no such op (e.g.
    mlp_control has no conv2d → no kernel_conv2d_mlp_control symbol)."""
    parts = ["\n/* ---------- parallel_for wrappers (Path 2 — skeleton-driven) ---------- */"]
    parts.append("#ifdef AGENTS_USE_POOL")
    parts.append('#include "agents_pool.h"')
    parts.append("#endif")
    for op in sorted(_PARALLELIZED_OPS & used_ops):
        parts.append(_PARALLEL_WRAPPER_TEMPLATES[op].format(mid=mid))
    return "\n".join(parts)




def _mid(model_name: str) -> str:
    """Model identifier — c-safe lowercase form used as a prefix on every
    globally-visible symbol the skeleton emits. Drives symbol-mangling so
    multiple models can co-exist in one binary."""
    return _c_ident(model_name)


def _umid(model_name: str) -> str:
    """Uppercase model identifier for #define macros."""
    return _c_ident(model_name).upper()


def _weight_name(model_name: str, weight_key: str) -> str:
    """Mangled weight-blob symbol name: <model>_<weight_key>."""
    return f"{_mid(model_name)}_{_c_ident(weight_key)}"


def emit_weights(model_name: str, weights: dict[str, np.ndarray], out_dir: str) -> None:
    keys = sorted(weights.keys())
    h_lines = [HEADER, "#pragma once", "",
               "#include <stdint.h>",
               "", "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    for k in keys:
        ident = _weight_name(model_name, k)
        c_type, _ = _np_to_c_dtype(weights[k].dtype)
        size = weights[k].size
        h_lines.append(f"extern const {c_type} {ident}[{size}];")
    h_lines += ["", "#ifdef __cplusplus", "}", "#endif", ""]
    with open(os.path.join(out_dir, "weights.h"), "w") as f:
        f.write("\n".join(h_lines))

    c_lines = [HEADER, "#include <stdint.h>", '#include "weights.h"', ""]
    for k in keys:
        ident = _weight_name(model_name, k)
        arr = weights[k]
        c_type, _ = _np_to_c_dtype(arr.dtype)
        c_lines.append(f"const {c_type} {ident}[{arr.size}] = {{")
        if arr.dtype in (np.float32, np.float16):
            # fp16 weights: widen to fp32 for the literal text (lossless),
            # implicit narrow happens at compile time when initializing the
            # _Float16 array.
            c_lines += _array_lines(arr)
        else:
            c_lines += _array_lines_int(arr)
        c_lines.append("};")
        c_lines.append("")
    with open(os.path.join(out_dir, "weights.c"), "w") as f:
        f.write("\n".join(c_lines))


def _shape_str(op: dict) -> str:
    """Stable, parseable per-op shape string for the profile CSV.

    Lists are joined with `|` (rather than printed as Python list literals)
    so the comma-delimited CSV parser doesn't get confused — e.g. a cat3
    op with C_inputs=[16, 16, 16] becomes ``C_inputs=16|16|16``.
    """
    sh = op.get("shape", {})
    parts: list[str] = []
    for k in sh:
        v = sh[k]
        if isinstance(v, (list, tuple)):
            v = "|".join(str(x) for x in v)
        parts.append(f"{k}={v}")
    return ";".join(parts)


def emit_model(ir: dict[str, Any], out_dir: str) -> None:
    in_tensor = ir["input"]["tensor"]   # first (or only) input name
    out_field = ir["output"]
    out_tensors_list: list[str] = (
        list(out_field["tensors"]) if out_field.get("tensors") else [out_field["tensor"]]
    )
    tensors = ir["tensors"]
    in_c_type = _dtype_to_c(tensors[in_tensor]["dtype"])
    # Build input offset map: {tensor_name: flat_offset_in_packed_input_buffer}.
    # Single-input models have no "packed_inputs" key — offset is always 0.
    if "packed_inputs" in ir["input"]:
        input_offsets: dict[str, int] = {
            p["name"]: p["offset"] for p in ir["input"]["packed_inputs"]
        }
        in_size = sum(p["size"] for p in ir["input"]["packed_inputs"])
    else:
        input_offsets = {in_tensor: 0}
        in_size = _prod(tensors[in_tensor]["shape"])
    input_names_set = set(input_offsets.keys())
    model_name = ir["name"]
    mid = _mid(model_name)
    umid = _umid(model_name)
    # All outputs must share a dtype (we concatenate into one output buffer).
    out_dtypes = {tensors[t]["dtype"] for t in out_tensors_list}
    if len(out_dtypes) != 1:
        raise NotImplementedError(
            f"multi-output models with mixed dtypes not supported: {out_dtypes}"
        )
    out_c_type = _dtype_to_c(next(iter(out_dtypes)))
    # Multi-output: concatenate outputs into a single output buffer in order.
    out_sizes = [_prod(tensors[t]["shape"]) for t in out_tensors_list]
    out_offsets = [sum(out_sizes[:i]) for i in range(len(out_sizes))]
    out_size = sum(out_sizes)
    out_tensor_to_offset = dict(zip(out_tensors_list, out_offsets))

    # `view` ops (flatten / dropout-in-eval) do not generate a kernel call —
    # the output tensor name aliases the input's buffer. Build the alias map
    # before assigning intermediate buffers so views never get their own.
    aliases: dict[str, str] = {}
    # Offset aliases: tensor → (base_tensor_name, element_offset). Used by
    # chunk2_c1 to express "y0 is the first half of cv1_out, y1 is the
    # second half" without copying — generated C just uses pointer math
    # (`buf_cv1_out + 0` vs `buf_cv1_out + c_each*H*W`). The aliased
    # tensors don't need their own intermediate buffers.
    offset_aliases: dict[str, tuple[str, int]] = {}
    def resolve_alias(name: str) -> str:
        seen: set[str] = set()
        while name in aliases:
            if name in seen:
                raise RuntimeError(f"alias cycle through {name}")
            seen.add(name)
            name = aliases[name]
        return name
    for op in ir["ops"]:
        if op["op"] == "view":
            aliases[op["outputs"][0]] = op["inputs"][0]
        elif op["op"] == "chunk2_c1":
            # Two outputs: first half at offset 0, second half at offset
            # c_each*H*W (in floats — pointer arithmetic on the base type).
            base = op["inputs"][0]
            sh = op["shape"]
            elem_offset = sh["c_each"] * sh["H"] * sh["W"]
            offset_aliases[op["outputs"][0]] = (base, 0)
            offset_aliases[op["outputs"][1]] = (base, elem_offset)

    # Number of ops that actually emit a kernel call (used to size the profile
    # record array). chunk2_c1 is a no-op at runtime (just sets up offset
    # aliases at codegen time), so it doesn't contribute either.
    _zero_cost_ops = {"view", "chunk2_c1"}
    op_count = sum(1 for op in ir["ops"] if op["op"] not in _zero_cost_ops)
    used_ops = {op["op"] for op in ir["ops"] if op["op"] not in _zero_cost_ops}

    # All exported symbols are mangled by model name (model_<mid>_*,
    # MODEL_<UMID>_*) so multiple models can co-exist in one binary.
    # Unmangled aliases (model_input_t, run_model, MODEL_NAME, ...) are
    # provided under #ifndef AGENTS_DISABLE_UNMANGLED for the
    # single-model harness's convenience. The multi-model harness defines
    # AGENTS_DISABLE_UNMANGLED before any model.h to prevent collisions.
    h = f"""{HEADER}
#pragma once

#include <stddef.h>
#include <stdint.h>

/* Mangled name macros (always defined). */
#define MODEL_{umid}_NAME         "{model_name}"
#define MODEL_{umid}_INPUT_SIZE   {in_size}
#define MODEL_{umid}_OUTPUT_SIZE  {out_size}
#define MODEL_{umid}_OP_COUNT     {op_count}
#define MODEL_{umid}_QUANT        "{ir.get("quant", "fp32")}"

/* Mangled I/O scalar types. */
typedef {in_c_type}  model_{mid}_input_t;
typedef {out_c_type} model_{mid}_output_t;

#ifdef __cplusplus
extern "C" {{
#endif

/* Per-kernel profile record. Populated by run_model_{mid}() — one entry per
 * kernel invocation, in execution order. `cycles` is rdcycle delta
 * (per-hart mcycle CSR — high-res; cross-hart wall time is reported
 * separately via model_<mid>_wall_cycles()). */
typedef struct {{
    int dispatch_id;    /* IR-assigned dispatch id (matches graph.json) */
    const char *name;   /* node name from IR (e.g. "fc1") */
    const char *op;     /* op kind (e.g. "linear", "linear_s8") */
    const char *shape;  /* shape descriptor, e.g. "M=1;K=16;N=32" */
    unsigned long cycles;
}} model_{mid}_op_record_t;

/* `pool` is an optional agents_pool_t (typed as void* here so this
 * header doesn't pull in agents_pool.h — single-model harness uses
 * NULL). Sequential kernel bodies ignore it; the parallel-for wrapper
 * (emitted by a later pipeline stage) casts and dispatches onto it. */
void run_model_{mid}(const model_{mid}_input_t *input,
                     model_{mid}_output_t *output,
                     void *pool);

/* Per-dispatch state passed to dispatch_<mid>_<id>() invocations.
 * Lives on the stack of run_model_{mid}() in the straight-line path,
 * or is owned by the schedule-driven runtime when it walks an XPU-RT
 * dispatch table. Intermediate buffers are file-static (see model.c)
 * and outlive any individual dispatch call. */
typedef struct {{
    const model_{mid}_input_t *input;
    model_{mid}_output_t      *output;
    void                       *pool;
}} model_{mid}_state_t;

typedef void (*model_{mid}_dispatch_fn)(model_{mid}_state_t *);

/* One invoke fn per dispatch_id, indexed in execution order
 * (= IR's `dispatches` array order). The schedule-driven runtime uses
 * this to call individual dispatches out-of-order; the straight-line
 * run_model_{mid}() walks it from 0..N-1. */
extern const model_{mid}_dispatch_fn
    MODEL_{umid}_DISPATCH_FNS[MODEL_{umid}_OP_COUNT];

/* Reset profile counter before invoking dispatches via the table.
 * run_model_{mid}() does this internally; the schedule-driven runtime
 * must call it once per inference. */
void model_{mid}_reset_profile(void);

/* Set the wall-clock delta for the most recent inference. The
 * schedule-driven runtime measures it externally (since it owns the
 * outer loop) and reports it via this setter — keeps the
 * model_{mid}_wall_cycles() reader consistent across both run paths. */
void model_{mid}_set_wall_cycles(unsigned long c);

/* Returns pointer to the static profile array; *count gets the number of
 * records written by the most recent run_model_{mid}() call. */
const model_{mid}_op_record_t *model_{mid}_profile_records(int *count);

/* Wall-clock cycles for the most recent run_model_{mid}() call. Sourced
 * from k_cycle_get_64() (mtime on RISC-V) — lower resolution than the
 * per-op rdcycle deltas above, but cross-hart-correct. */
unsigned long model_{mid}_wall_cycles(void);

#ifdef __cplusplus
}}
#endif

/* ---------------------------------------------------------------------- */
/* Unmangled aliases for single-model use. The multi-model harness should */
/* `#define AGENTS_DISABLE_UNMANGLED` before including any model.h to     */
/* avoid name collisions across models.                                   */
/* ---------------------------------------------------------------------- */
#ifndef AGENTS_DISABLE_UNMANGLED
#define MODEL_NAME            MODEL_{umid}_NAME
#define MODEL_INPUT_SIZE      MODEL_{umid}_INPUT_SIZE
#define MODEL_OUTPUT_SIZE     MODEL_{umid}_OUTPUT_SIZE
#define MODEL_OP_COUNT        MODEL_{umid}_OP_COUNT
#define MODEL_QUANT           MODEL_{umid}_QUANT
typedef model_{mid}_input_t   model_input_t;
typedef model_{mid}_output_t  model_output_t;
typedef model_{mid}_op_record_t model_op_record_t;
#define run_model             run_model_{mid}
#define model_profile_records model_{mid}_profile_records
#define model_wall_cycles     model_{mid}_wall_cycles
#define model_set_wall_cycles model_{mid}_set_wall_cycles
#define model_reset_profile   model_{mid}_reset_profile
#define model_dispatch_fns    MODEL_{umid}_DISPATCH_FNS
typedef model_{mid}_state_t       model_state_t;
typedef model_{mid}_dispatch_fn   model_dispatch_fn;
#endif
"""
    with open(os.path.join(out_dir, "model.h"), "w") as f:
        f.write(h)

    # Allocate one buffer per intermediate tensor (skip all inputs, any final
    # output tensor, and any tensor that is just a view alias).
    # Definitions live in a sibling buffers.c so every backend's copy of
    # model.c sees the SAME storage via extern (see _buf_name for why).
    out_tensor_set = set(out_tensors_list)
    intermediates = [
        t for t in tensors
        if t not in input_names_set and t not in out_tensor_set
        and t not in aliases and t not in offset_aliases
    ]
    buf_defs: list[str] = []   # for buffers.c (definitions, no `static`)
    buf_externs: list[str] = []  # for model.c (declarations)
    for t in intermediates:
        size = _prod(tensors[t]["shape"])
        c_type = _dtype_to_c(tensors[t]["dtype"])
        buf_defs.append(f"{c_type} {_buf_name(mid, t)}[{size}];")
        buf_externs.append(f"extern {c_type} {_buf_name(mid, t)}[{size}];")

    def ptr_for(tensor: str, role: str) -> str:
        tensor = resolve_alias(tensor)
        if tensor in offset_aliases:
            base, off = offset_aliases[tensor]
            base_ptr = ptr_for(base, role)
            return base_ptr if off == 0 else f"({base_ptr} + {off})"
        if tensor in input_offsets:
            off = input_offsets[tensor]
            return "input" if off == 0 else f"(input + {off})"
        if tensor in out_tensor_to_offset:
            off = out_tensor_to_offset[tensor]
            return "output" if off == 0 else f"(output + {off})"
        return _buf_name(mid, tensor)

    call_blocks: list[str] = []  # legacy — no longer used in run_model body
    dispatch_fns: list[str] = []
    invoke_table_rows: list[str] = []
    for op in ir["ops"]:
        if op["op"] in _zero_cost_ops:
            # view / chunk2_c1: no kernel call. Aliases were set up above
            # (plain aliases for view, offset aliases for chunk2_c1).
            continue
        out_ptr = ptr_for(op["outputs"][0], "out")
        shape_lit = _shape_str(op)
        if op["op"] == "linear":
            in_ptr = ptr_for(op["inputs"][0], "in")
            w = _weight_name(model_name, op["weight"])
            b = _weight_name(model_name, op["bias"]) if op.get("bias") else "NULL"
            sh = op["shape"]
            # Parallel-for variant: dispatches the outer N dimension onto
            # `pool` when M==1 and the pool has >1 worker. In single-model
            # builds (AGENTS_USE_POOL undefined) the wrapper is a static
            # inline that just calls kernel_linear_<mid>() directly.
            call = (
                f"parallel_linear(pool, {in_ptr}, {w}, {b}, {out_ptr}, "
                f"{sh['M']}, {sh['K']}, {sh['N']})"
            )
        elif op["op"] == "relu":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_relu({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "elu":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            alpha = op.get("alpha", 1.0)
            call = f"kernel_elu({in_ptr}, {out_ptr}, {n}, {_f32(alpha)})"
        elif op["op"] == "conv2d":
            in_ptr = ptr_for(op["inputs"][0], "in")
            w = _weight_name(model_name, op["weight"])
            b = _weight_name(model_name, op["bias"]) if op.get("bias") else "NULL"
            sh = op["shape"]
            # Parallel-for variant: dispatches the outer OC dimension onto
            # `pool` when N==1 and the pool has >1 worker. Falls back to
            # the sequential kernel inside the wrapper otherwise.
            call = (
                f"parallel_conv2d(pool, {in_ptr}, {w}, {b}, {out_ptr}, "
                f"{sh['N']}, {sh['IC']}, {sh['IH']}, {sh['IW']}, "
                f"{sh['OC']}, {sh['KH']}, {sh['KW']}, "
                f"{sh['SH']}, {sh['SW']}, {sh['PH']}, {sh['PW']})"
            )
        elif op["op"] == "maxpool2d":
            in_ptr = ptr_for(op["inputs"][0], "in")
            sh = op["shape"]
            PH, PW = sh.get("PH", 0), sh.get("PW", 0)
            DH, DW = sh.get("DH", 1), sh.get("DW", 1)
            call = (
                f"kernel_maxpool2d({in_ptr}, {out_ptr}, "
                f"{sh['N']}, {sh['C']}, {sh['IH']}, {sh['IW']}, "
                f"{sh['KH']}, {sh['KW']}, {sh['SH']}, {sh['SW']}, "
                f"{PH}, {PW}, {DH}, {DW})"
            )
        elif op["op"] == "add":
            a_ptr = ptr_for(op["inputs"][0], "in")
            b_ptr = ptr_for(op["inputs"][1], "in")
            n = op["shape"]["n"]
            call = f"kernel_add({a_ptr}, {b_ptr}, {out_ptr}, {n})"
        elif op["op"] == "batchnorm2d":
            in_ptr = ptr_for(op["inputs"][0], "in")
            s = _weight_name(model_name, op["weight"])
            b = _weight_name(model_name, op["bias"])
            sh = op["shape"]
            call = (
                f"kernel_batchnorm2d({in_ptr}, {s}, {b}, {out_ptr}, "
                f"{sh['N']}, {sh['C']}, {sh['H']}, {sh['W']})"
            )
        elif op["op"] == "sigmoid":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_sigmoid({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "silu":
            # YOLOv8 Conv block activation. SiLU(x) = x * sigmoid(x).
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_silu({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "upsample_nearest":
            # YOLOv8 neck nearest-neighbor 2× upsample.
            in_ptr = ptr_for(op["inputs"][0], "in")
            sh = op["shape"]
            call = (
                f"kernel_upsample_nearest({in_ptr}, {out_ptr}, "
                f"{sh['N']}, {sh['C']}, {sh['IH']}, {sh['IW']}, "
                f"{sh['scale']})"
            )
        elif op["op"] in ("cat2_c1", "cat3_c1", "cat4_c1"):
            # Channel-wise concat. Per-input channel counts are baked into
            # the call so the kernel can compute its destination offsets
            # without a runtime lookup table.
            sh = op["shape"]
            in_ptrs = [ptr_for(n, "in") for n in op["inputs"]]
            cs = sh["C_inputs"]
            call = (
                f"kernel_{op['op']}("
                + ", ".join(f"{p}, {c}" for p, c in zip(in_ptrs, cs))
                + f", {out_ptr}, {sh['N']}, {sh['H']}, {sh['W']})"
            )
        elif op["op"] == "chunk2_c1":
            # No-op at runtime: the two halves are aliases of the input
            # buffer at offsets 0 and c_each*H*W. Codegen handles this via
            # `offset_aliases` (see below) — emit no kernel call.
            call = None
        elif op["op"] == "relu6":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_relu6({in_ptr}, {out_ptr}, {n})"
        # KernelBench Phase 2 activations.
        elif op["op"] == "leaky_relu":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            slope = op.get("negative_slope", 0.01)
            call = (
                f"kernel_leaky_relu({in_ptr}, {out_ptr}, {n}, {_f32(slope)})"
            )
        elif op["op"] == "tanh":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_tanh({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "gelu":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_gelu({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "gelu_exact":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_gelu_exact({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "selu":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_selu({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "hardsigmoid":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_hardsigmoid({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "softplus":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_softplus({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "softsign":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_softsign({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "swish":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_swish({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "hardtanh":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            mn = op.get("min_val", -1.0)
            mx = op.get("max_val",  1.0)
            call = (
                f"kernel_hardtanh({in_ptr}, {out_ptr}, {n}, "
                f"{_f32(mn)}, {_f32(mx)})"
            )
        # KernelBench Phase 2 reductions (sum/mean/max/min/prod/argmax/argmin
        # over a single dimension). All share the (outer, reduce, inner) shape.
        elif op["op"] in ("sum_dim", "mean_dim", "max_dim", "min_dim",
                          "prod_dim", "argmax_dim", "argmin_dim"):
            in_ptr = ptr_for(op["inputs"][0], "in")
            sh = op["shape"]
            call = (
                f"kernel_{op['op']}({in_ptr}, {out_ptr}, "
                f"{sh['outer']}, {sh['reduce']}, {sh['inner']})"
            )
        elif op["op"] in ("l1_norm", "l2_norm"):
            in_ptr = ptr_for(op["inputs"][0], "in")
            sh = op["shape"]
            call = (
                f"kernel_{op['op']}({in_ptr}, {out_ptr}, "
                f"{sh['outer']}, {sh['reduce']}, {sh['inner']})"
            )
        elif op["op"] == "frobenius_norm":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_frobenius_norm({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "conv2d_dw":
            in_ptr = ptr_for(op["inputs"][0], "in")
            w = _weight_name(model_name, op["weight"])
            b = _weight_name(model_name, op["bias"]) if op.get("bias") else "NULL"
            sh = op["shape"]
            call = (
                f"kernel_conv2d_dw({in_ptr}, {w}, {b}, {out_ptr}, "
                f"{sh['N']}, {sh['C']}, {sh['IH']}, {sh['IW']}, "
                f"{sh['KH']}, {sh['KW']}, {sh['SH']}, {sh['SW']}, "
                f"{sh['PH']}, {sh['PW']})"
            )
        elif op["op"] == "adaptive_avg_pool2d":
            in_ptr = ptr_for(op["inputs"][0], "in")
            sh = op["shape"]
            call = (
                f"kernel_adaptive_avg_pool2d({in_ptr}, {out_ptr}, "
                f"{sh['N']}, {sh['C']}, {sh['IH']}, {sh['IW']})"
            )
        elif op["op"] == "linear_s8":
            in_ptr = ptr_for(op["inputs"][0], "in")
            w = _weight_name(model_name, op["weight"])
            b = _weight_name(model_name, op["bias"]) if op.get("bias") else "NULL"
            sh = op["shape"]
            q = op["quant"]
            call = (
                f"kernel_linear_s8({in_ptr}, {w}, {b}, {out_ptr}, "
                f"{sh['M']}, {sh['K']}, {sh['N']}, "
                f"{q['input_offset']}, {q['filter_offset']}, "
                f"{q['output_offset']}, "
                f"{q['output_multiplier']}, {q['output_shift']}, "
                f"{q['activation_min']}, {q['activation_max']})"
            )
        elif op["op"] == "relu_s8":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_relu_s8({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "conv2d_s8":
            in_ptr = ptr_for(op["inputs"][0], "in")
            w = _weight_name(model_name, op["weight"])
            b = _weight_name(model_name, op["bias"]) if op.get("bias") else "NULL"
            sh = op["shape"]
            q = op["quant"]
            call = (
                f"kernel_conv2d_s8({in_ptr}, {w}, {b}, {out_ptr}, "
                f"{sh['N']}, {sh['IC']}, {sh['IH']}, {sh['IW']}, "
                f"{sh['OC']}, {sh['KH']}, {sh['KW']}, "
                f"{sh['SH']}, {sh['SW']}, {sh['PH']}, {sh['PW']}, "
                f"{q['input_offset']}, {q['filter_offset']}, "
                f"{q['output_offset']}, "
                f"{q['output_multiplier']}, {q['output_shift']}, "
                f"{q['activation_min']}, {q['activation_max']})"
            )
        elif op["op"] == "maxpool2d_s8":
            in_ptr = ptr_for(op["inputs"][0], "in")
            sh = op["shape"]
            PH, PW = sh.get("PH", 0), sh.get("PW", 0)
            DH, DW = sh.get("DH", 1), sh.get("DW", 1)
            call = (
                f"kernel_maxpool2d_s8({in_ptr}, {out_ptr}, "
                f"{sh['N']}, {sh['C']}, {sh['IH']}, {sh['IW']}, "
                f"{sh['KH']}, {sh['KW']}, {sh['SH']}, {sh['SW']}, "
                f"{PH}, {PW}, {DH}, {DW})"
            )
        elif op["op"] == "add_s8":
            a_ptr = ptr_for(op["inputs"][0], "in")
            b_ptr = ptr_for(op["inputs"][1], "in")
            n = op["shape"]["n"]
            q = op["quant"]
            call = (
                f"kernel_add_s8({a_ptr}, {b_ptr}, {out_ptr}, {n}, "
                f"{_f32(q['scale_a'])}, {_f32(q['scale_b'])}, "
                f"{_f32(q['scale_out'])}, "
                f"{q['activation_min']}, {q['activation_max']})"
            )
        elif op["op"] == "batchnorm2d_s8":
            in_ptr = ptr_for(op["inputs"][0], "in")
            s = _weight_name(model_name, op["weight"])
            b = _weight_name(model_name, op["bias"])
            sh = op["shape"]
            q = op["quant"]
            call = (
                f"kernel_batchnorm2d_s8({in_ptr}, {s}, {b}, {out_ptr}, "
                f"{sh['N']}, {sh['C']}, {sh['H']}, {sh['W']}, "
                f"{_f32(q['scale_in'])}, {_f32(q['scale_out'])}, "
                f"{q['activation_min']}, {q['activation_max']})"
            )
        elif op["op"] == "sigmoid_s8":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            q = op["quant"]
            call = (
                f"kernel_sigmoid_s8({in_ptr}, {out_ptr}, {n}, "
                f"{_f32(q['scale_in'])}, {_f32(q['scale_out'])}, "
                f"{q['activation_min']}, {q['activation_max']})"
            )
        # ---- fp16 (half-precision) variants. Same dataflow as fp32 but
        #      the kernel signature takes _Float16 storage. No quantization
        #      knobs — that's what fp16 is FOR. ----
        elif op["op"] == "relu_f16":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_relu_f16({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "elu_f16":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            alpha = op.get("alpha", 1.0)
            call = (
                f"kernel_elu_f16({in_ptr}, {out_ptr}, {n}, {_f32(alpha)})"
            )
        elif op["op"] == "sigmoid_f16":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_sigmoid_f16({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "batchnorm2d_f16":
            in_ptr = ptr_for(op["inputs"][0], "in")
            s = _weight_name(model_name, op["weight"])
            b = _weight_name(model_name, op["bias"])
            sh = op["shape"]
            call = (
                f"kernel_batchnorm2d_f16({in_ptr}, {s}, {b}, {out_ptr}, "
                f"{sh['N']}, {sh['C']}, {sh['H']}, {sh['W']})"
            )
        elif op["op"] == "maxpool2d_f16":
            in_ptr = ptr_for(op["inputs"][0], "in")
            sh = op["shape"]
            PH, PW = sh.get("PH", 0), sh.get("PW", 0)
            DH, DW = sh.get("DH", 1), sh.get("DW", 1)
            call = (
                f"kernel_maxpool2d_f16({in_ptr}, {out_ptr}, "
                f"{sh['N']}, {sh['C']}, {sh['IH']}, {sh['IW']}, "
                f"{sh['KH']}, {sh['KW']}, {sh['SH']}, {sh['SW']}, "
                f"{PH}, {PW}, {DH}, {DW})"
            )
        elif op["op"] == "conv2d_f16":
            in_ptr = ptr_for(op["inputs"][0], "in")
            w = _weight_name(model_name, op["weight"])
            b = _weight_name(model_name, op["bias"]) if op.get("bias") else "NULL"
            sh = op["shape"]
            call = (
                f"kernel_conv2d_f16({in_ptr}, {w}, {b}, {out_ptr}, "
                f"{sh['N']}, {sh['IC']}, {sh['IH']}, {sh['IW']}, "
                f"{sh['OC']}, {sh['KH']}, {sh['KW']}, "
                f"{sh['SH']}, {sh['SW']}, {sh['PH']}, {sh['PW']})"
            )
        elif op["op"] in ("matmul", "matmul_ta", "matmul_tb", "matmul_tatb",
                           "matmul_f16", "matmul_ta_f16", "matmul_tb_f16", "matmul_tatb_f16"):
            a_ptr = ptr_for(op["inputs"][0], "in")
            b_ptr = ptr_for(op["inputs"][1], "in")
            sh = op["shape"]
            call = (
                f"kernel_{op['op']}({a_ptr}, {b_ptr}, {out_ptr}, "
                f"{sh['M']}, {sh['K']}, {sh['N']})"
            )
        elif op["op"] in ("bmm", "bmm_f16"):
            a_ptr = ptr_for(op["inputs"][0], "in")
            b_ptr = ptr_for(op["inputs"][1], "in")
            sh = op["shape"]
            call = (
                f"kernel_{op['op']}({a_ptr}, {b_ptr}, {out_ptr}, "
                f"{sh['batch']}, {sh['M']}, {sh['K']}, {sh['N']})"
            )
        else:
            raise NotImplementedError(f"unsupported op {op['op']}")
        # Mangle the kernel call: every kernels.c emits kernel_<op>_<mid>
        # (set via emit_kernels_h/c's model_name arg) so multiple models can
        # link side-by-side without colliding on bare kernel_<op> symbols.
        # Parallelized ops route through a static parallel_<op>() wrapper
        # whose body already calls the mangled kernel — skip the rewrite
        # so we don't accidentally mangle the wrapper name itself.
        if op["op"] not in _PARALLELIZED_OPS:
            call = call.replace(
                f"kernel_{op['op']}(", f"kernel_{op['op']}_{mid}(", 1
            )
        # dispatch_id comes from the IR (assigned by extract_graph's
        # _annotate_dispatches). Propagating it here means the C-level
        # profile, the host-side CSV writer, and the IR all agree on
        # the same dispatch numbering — single source of truth.
        dispatch_id = op["dispatch_id"]
        # Rewrite "input"/"output" pointer references so they read from
        # the model_<mid>_state_t the dispatch fn is invoked with. Buffer
        # references (buf_<...>) stay as-is — those are file-static.
        per_disp_call = (call
                         .replace("(input + ", "(s->input + ")
                         .replace("input,", "s->input,")
                         .replace("input)", "s->input)")
                         .replace("output,", "s->output,")
                         .replace("output)", "s->output)")
                         .replace("(output + ", "(s->output + ")
                         .replace("(pool, ", "(s->pool, "))
        dispatch_fns.append(
            f"static void dispatch_{mid}_{dispatch_id}(model_{mid}_state_t *s) {{\n"
            f"    unsigned long _s = rdcycle();\n"
            f"    {per_disp_call};\n"
            f"    unsigned long _e = rdcycle();\n"
            f"    int slot = n_++;\n"
            f'    records_[slot].dispatch_id = {dispatch_id};\n'
            f'    records_[slot].name   = "{op["name"]}";\n'
            f'    records_[slot].op     = "{op["op"]}";\n'
            f'    records_[slot].shape  = "{shape_lit}";\n'
            f"    records_[slot].cycles = _e - _s;\n"
            f"}}"
        )
        invoke_table_rows.append(f"    dispatch_{mid}_{dispatch_id},")

    c = f"""{HEADER}
#include <stddef.h>
#include <stdint.h>
#include <zephyr/kernel.h>   /* for k_cycle_get_64() — static inline in this header */
#include "model.h"
#include "kernels.h"
#include "weights.h"

/* Per-op timer: per-hart mcycle CSR. High resolution (one count per
 * retired instruction) and accurate enough for relative comparisons
 * between ops on spike. Caveat: on real Chipyard silicon mcycle pauses
 * during WFI, so when the master thread sleeps waiting on threadpool
 * workers this UNDERCOUNTS wall time. We additionally measure
 * end-to-end wall cycles via k_cycle_get_64() (mtime) — that's the
 * cross-hart-correct number; per-op rdcycle is only sound when run
 * sequentially or while the master itself participates in parallel
 * dispatch (which pthreadpool_parallelize_1d does). */
static inline unsigned long rdcycle(void)
{{
    unsigned long cc;
    __asm__ volatile("rdcycle %0" : "=r"(cc));
    return cc;
}}
{_emit_parallel_wrappers(mid, used_ops)}

/* Per-model intermediate buffers. Defined in a sibling buffers.c (one
 * TU per model, NOT per backend) so the heterogeneous harness's two
 * model.c TUs (rvv + scalar) share the same scratch — otherwise each
 * backend's file-static buf_* would shadow the other and cross-backend
 * dispatches would read zeroed scratch. Names are mangled with the
 * model id (buf_<mid>_*) so different models don't collide at link. */
{chr(10).join(buf_externs)}

/* File-static — invisible across TUs, no need to mangle. Locals to this .c. */
static model_{mid}_op_record_t records_[MODEL_{umid}_OP_COUNT];
static int n_;
/* Wall-clock cycles for the most recent run_model_<mid>() call, sourced
 * from k_cycle_get_64() (mtime). Cross-hart correct, lower resolution
 * than per-op rdcycle. */
static unsigned long wall_cycles_;

/* ---------- per-dispatch invoke fns (one per non-view IR op) ----------- */
{chr(10).join(dispatch_fns)}

/* Invoke table indexed by IR dispatch_id. The schedule-driven runtime
 * uses this to call individual dispatches out-of-order; the
 * straight-line run_model_{mid}() below walks it from 0..N-1. */
const model_{mid}_dispatch_fn
MODEL_{umid}_DISPATCH_FNS[MODEL_{umid}_OP_COUNT] = {{
{chr(10).join(invoke_table_rows)}
}};

void model_{mid}_reset_profile(void) {{
    n_ = 0;
}}

void model_{mid}_set_wall_cycles(unsigned long c) {{
    wall_cycles_ = c;
}}

void run_model_{mid}(const model_{mid}_input_t *input,
                     model_{mid}_output_t *output,
                     void *pool) {{
    model_{mid}_state_t s = {{ .input = input, .output = output, .pool = pool }};
    n_ = 0;
    unsigned long _wall_s = (unsigned long)k_cycle_get_64();
    for (int i = 0; i < MODEL_{umid}_OP_COUNT; i++) {{
        MODEL_{umid}_DISPATCH_FNS[i](&s);
    }}
    wall_cycles_ = (unsigned long)k_cycle_get_64() - _wall_s;
}}

const model_{mid}_op_record_t *model_{mid}_profile_records(int *count) {{
    *count = n_;
    return records_;
}}

unsigned long model_{mid}_wall_cycles(void) {{
    return wall_cycles_;
}}
"""
    with open(os.path.join(out_dir, "model.c"), "w") as f:
        f.write(c)

    # Sibling buffers.c — definitions for the intermediate scratch
    # buffers that model.c references via extern. Compiled exactly once
    # per model (NOT per backend) so heterogeneous binaries share a
    # single instance across rvv/scalar/etc. dispatch tables.
    buf_c = f"""{HEADER}
/*
 * Per-model intermediate buffer storage. Definitions only — declarations
 * live alongside the dispatch fns in model.c. This file must be linked
 * EXACTLY ONCE per model into any binary (single-backend, multi-model,
 * or heterogeneous). The heterogeneous harness compiles model.c per
 * backend but pulls in this TU only once, so all backends end up
 * pointing at the same scratch storage and cross-backend dispatches
 * within one network see consistent intermediate state.
 */

#include <stdint.h>

{chr(10).join(buf_defs)}
"""
    with open(os.path.join(out_dir, "buffers.c"), "w") as f:
        f.write(buf_c)


def emit_test_io(model_name: str, io_npz: str, out_dir: str) -> None:
    """Emit per-model test inputs + goldens.

    Layout:
      test_io.h       — extern declarations + size constants. No data.
      test_io.S       — uses .incbin to pull the raw .bin files into
                        rodata at link time (the assembler streams them
                        verbatim — no parsing cost).
      test_input.bin  — raw little-endian fp32/int8 bytes from io.npz.
      test_golden.bin — same.

    Why .incbin instead of `static const T arr[N] = { 0.123f, ... };`:
    the latter forces the C compiler to parse one decimal literal per
    element. KernelBench's stock shapes are big — 33_BatchNorm at
    16x64x256x256 = 67M floats = ~2 GB of decimal text — and cc1
    chokes (we measured 22 GB RAM, no sign of finishing). The
    .incbin path makes test_io effectively zero-cost at compile time
    regardless of size.
    """
    mid = _mid(model_name)
    umid = _umid(model_name)
    data = np.load(io_npz)
    inp = np.ascontiguousarray(data["input"].reshape(-1))
    out = np.ascontiguousarray(data["output"].reshape(-1))
    in_c, _ = _np_to_c_dtype(inp.dtype)
    out_c, _ = _np_to_c_dtype(out.dtype)

    # 1) raw binary blobs.
    in_bin = os.path.join(out_dir, "test_input.bin")
    out_bin = os.path.join(out_dir, "test_golden.bin")
    inp.tofile(in_bin)
    out.tofile(out_bin)

    # 2) test_io.S — assembler with .incbin pointing at the .bin files.
    # Use absolute paths so the assembler resolves them regardless of
    # the build's working directory or -I search path. Symbols are
    # .globl so the extern decls in test_io.h resolve.
    in_sym  = f"model_{mid}_test_input"
    out_sym = f"model_{mid}_test_golden"
    in_bin_abs  = os.path.abspath(in_bin)
    out_bin_abs = os.path.abspath(out_bin)
    s_lines = [
        f"/* @generated by agents/pipeline/generate_skeleton.py */",
        f"    .section .rodata",
        f"    .align 4",
        f"    .globl  {in_sym}",
        f"    .type   {in_sym}, @object",
        f"{in_sym}:",
        f'    .incbin "{in_bin_abs}"',
        f"    .size   {in_sym}, . - {in_sym}",
        f"",
        f"    .align 4",
        f"    .globl  {out_sym}",
        f"    .type   {out_sym}, @object",
        f"{out_sym}:",
        f'    .incbin "{out_bin_abs}"',
        f"    .size   {out_sym}, . - {out_sym}",
        f"",
    ]
    with open(os.path.join(out_dir, "test_io.S"), "w") as f:
        f.write("\n".join(s_lines))

    # 3) test_io.h — declarations only. Size macros stay #define so
    # they're constant-foldable; arrays are extern.
    h_lines = [
        HEADER,
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"/* Mangled (always defined). */",
        f"#define MODEL_{umid}_TEST_INPUT_LEN  {inp.size}",
        f"#define MODEL_{umid}_TEST_OUTPUT_LEN {out.size}",
        "",
        f"/* Definitions in test_io.S (.incbin from test_input.bin /",
        f" * test_golden.bin). Const so the linker can keep them in",
        f" * rodata; the assembler emits them in .rodata directly. */",
        f"extern const {in_c}  {in_sym}[MODEL_{umid}_TEST_INPUT_LEN];",
        f"extern const {out_c} {out_sym}[MODEL_{umid}_TEST_OUTPUT_LEN];",
        "",
        "/* Unmangled aliases for single-model use. The multi-model harness",
        " * defines AGENTS_DISABLE_UNMANGLED before including any test_io.h",
        " * to keep names from colliding. */",
        "#ifndef AGENTS_DISABLE_UNMANGLED",
        f"#define MODEL_TEST_INPUT_LEN  MODEL_{umid}_TEST_INPUT_LEN",
        f"#define MODEL_TEST_OUTPUT_LEN MODEL_{umid}_TEST_OUTPUT_LEN",
        f"#define model_test_input      {in_sym}",
        f"#define model_test_golden     {out_sym}",
        "#endif",
        "",
    ]
    with open(os.path.join(out_dir, "test_io.h"), "w") as f:
        f.write("\n".join(h_lines))


def generate(ir_path: str, weights_path: str, io_path: str, out_dir: str) -> None:
    os.makedirs(out_dir, exist_ok=True)
    with open(ir_path) as f:
        ir = json.load(f)
    weights = dict(np.load(weights_path))
    model_name = ir["name"]

    emit_weights(model_name, weights, out_dir)
    emit_model(ir, out_dir)
    emit_test_io(model_name, io_path, out_dir)

    files = ["weights.h", "weights.c", "model.h", "model.c",
             "buffers.c", "test_io.h"]
    for fn in files:
        print(f"wrote {os.path.join(out_dir, fn)}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ir", required=True, help="graph.json")
    ap.add_argument("--weights", required=True, help="weights.npz")
    ap.add_argument("--io", required=True, help="io.npz")
    ap.add_argument("--out-dir", required=True, help="harness src/ dir")
    args = ap.parse_args()
    generate(args.ir, args.weights, args.io, args.out_dir)


if __name__ == "__main__":
    main()
