"""Emit a multi-model main.c that runs N models sequentially and prints
each one's output + per-kernel profile between marker lines tagged with
the model name.

This is the orchestrator file the harness_multi/ CMakeLists.txt builds
into the binary. The single-model harness's main.c lives in
harness/src/main.c and is unchanged; this script's output is its
multi-model counterpart.

Usage:
    python -m agents.pipeline.generate_multi_main \\
        --models name1:/abs/path/to/model_dir1 name2:/abs/path/to/model_dir2 \\
        --out  /abs/path/to/multi_main.c
"""

from __future__ import annotations

import argparse
import json
import os


HEADER = "/* @generated by agents/pipeline/generate_multi_main.py — do not edit. */"


def _ir_for(model_dir: str) -> dict:
    """Locate graph.json for a model_dir (search the dir, then its parent)."""
    for cand in (
        os.path.join(model_dir, "graph.json"),
        os.path.join(os.path.dirname(model_dir.rstrip("/")), "graph.json"),
    ):
        if os.path.exists(cand):
            with open(cand) as f:
                return json.load(f)
    raise FileNotFoundError(f"could not find graph.json near {model_dir}")


def _emit(models: list[tuple[str, str]]) -> str:
    """Render multi_main.c source. `models` is a list of (name, model_dir) pairs."""
    # Preflight: every model_dir must have its mangled headers staged in the
    # build dir as <name>_model.h and <name>_test_io.h. CMake's configure_file
    # is responsible for that — this file just emits the includes.
    inc_lines: list[str] = []
    buf_decls: list[str] = []
    run_blocks: list[str] = []

    for name, model_dir in models:
        umid = name.replace(".", "_").replace("-", "_").upper()
        mid = name.replace(".", "_").replace("-", "_")
        inc_lines.append(f'#include "{name}_model.h"')
        inc_lines.append(f'#include "{name}_test_io.h"')

        buf_decls.append(
            f"static model_{mid}_output_t out_{mid}[MODEL_{umid}_OUTPUT_SIZE];"
        )

        run_blocks.append(f"""\
    /* --- {name} ----------------------------------------------------------- */
    printf("running model: {name}\\n");
    run_model_{mid}(model_{mid}_test_input, out_{mid}, (void *)pool);
    printf("=== AGENTS_OUTPUT_BEGIN [{name}] ===\\n");
    for (int i = 0; i < MODEL_{umid}_OUTPUT_SIZE; i++) {{
        printf("%.9g\\n", (double)out_{mid}[i]);
    }}
    printf("=== AGENTS_OUTPUT_END [{name}] ===\\n");
    {{
        int n_records = 0;
        const model_{mid}_op_record_t *records =
            model_{mid}_profile_records(&n_records);
        printf("=== AGENTS_PROFILE_BEGIN [{name}] ===\\n");
        printf("dispatch_id,name,op,shape,cycles\\n");
        for (int i = 0; i < n_records; i++) {{
            printf("%d,%s,%s,%s,%lu\\n",
                   records[i].dispatch_id,
                   records[i].name, records[i].op, records[i].shape,
                   records[i].cycles);
        }}
        printf("=== AGENTS_PROFILE_END [{name}] ===\\n");
    }}
    printf("=== AGENTS_WALL_CYCLES [{name}] === %lu\\n",
           model_{mid}_wall_cycles());
""")

    return f"""{HEADER}
/*
 * Multi-model harness entry point. Runs each model sequentially on its own
 * fixed test input, prints output + per-kernel profile between marker lines
 * tagged with the model name so the host-side spike_runner can disambiguate.
 *
 * AGENTS_DISABLE_UNMANGLED prevents each model's model.h from defining
 * unmangled aliases (run_model, model_input_t, MODEL_NAME, ...) that would
 * collide across models.
 *
 * The harness owns a single pthreadpool. It's created here and threaded
 * through every run_model_<name>() call so per-op kernels can dispatch
 * work onto it (intra-model parallelism). Kernels that are still
 * sequential simply ignore the handle.
 */

#define AGENTS_DISABLE_UNMANGLED

#include <stdio.h>
#include <stdlib.h>
#include <pthreadpool.h>
#include <zephyr/sys/reboot.h>

{chr(10).join(inc_lines)}

{chr(10).join(buf_decls)}

/* pthreadpool's memory.c calls posix_memalign() (non-Android, non-Win
 * branch). The picolibc object that supplies posix_memalign also
 * defines memalign + aligned_alloc, and Zephyr's COMMON_LIBC_MALLOC
 * already defines aligned_alloc -- which produces a duplicate-definition
 * link error. Defining memalign here forces the linker to satisfy the
 * memalign reference from this TU, so picolibc's combined object is
 * never pulled in. (samples/xnnpack avoids this implicitly via
 * CONFIG_GLIBCXX_LIBCPP, which we don't enable since we have no C++.)
 */
void *memalign(size_t alignment, size_t size)
{{
    return aligned_alloc(alignment, size);
}}

int posix_memalign(void **out, size_t alignment, size_t size)
{{
    void *p = aligned_alloc(alignment, size);
    if (p == NULL) {{
        return 12; /* ENOMEM */
    }}
    *out = p;
    return 0;
}}

int main(void)
{{
    printf("agents multi-model harness: %d models on %s\\n",
           {len(models)}, CONFIG_BOARD_TARGET);

    /* AGENTS_POOL_THREADS lets the build pick a fixed worker count; 0 (the
     * default) lets pthreadpool auto-pick CONFIG_MP_MAX_NUM_CPUS. The
     * sweep harness sets this per-run to compare 1- vs N-thread costs.
     */
#ifndef AGENTS_POOL_THREADS
#define AGENTS_POOL_THREADS 0
#endif
    pthreadpool_t pool = pthreadpool_create(AGENTS_POOL_THREADS);
    if (pool == NULL) {{
        printf("FATAL: pthreadpool_create returned NULL\\n");
        sys_reboot(SYS_REBOOT_COLD);
        return -1;
    }}
    printf("pthreadpool: %u threads\\n",
           (unsigned)pthreadpool_get_threads_count(pool));

{chr(10).join(run_blocks)}

    pthreadpool_destroy(pool);
    sys_reboot(SYS_REBOOT_COLD);
    return 0;
}}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--models", required=True, nargs="+",
                    help="<name>:<model_dir> pairs (model_dir = the per-target "
                         "generated/<target>/ dir that holds model.c, kernels.c, "
                         "weights.c, model.h, test_io.h)")
    ap.add_argument("--out", required=True, help="path for the emitted multi_main.c")
    args = ap.parse_args()

    pairs: list[tuple[str, str]] = []
    for spec in args.models:
        if ":" not in spec:
            raise SystemExit(f"--models entry must be name:dir, got {spec!r}")
        name, model_dir = spec.split(":", 1)
        if not os.path.isdir(model_dir):
            raise SystemExit(f"model_dir does not exist: {model_dir}")
        # Sanity-check the IR's recorded name matches the user-supplied name.
        ir = _ir_for(model_dir)
        ir_name = ir.get("name")
        if ir_name and ir_name != name:
            raise SystemExit(
                f"name mismatch: --models said {name!r} but graph.json "
                f"records {ir_name!r} for {model_dir}"
            )
        pairs.append((name, model_dir))

    src = _emit(pairs)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(src)
    print(f"wrote {args.out}  ({len(pairs)} models)")


if __name__ == "__main__":
    main()
