"""IR + weights + io -> driver/weight/test C files for the Zephyr harness.

Outputs (all marked @generated):
    model.h, model.c             driver: run_model(input, output)
    weights.h, weights.c         const float arrays for each weight
    test_io.h                    sample input + golden output for host compare

Kernels (kernels.h, kernels.c) are produced by a separate stage:
    agents/pipeline/generate_kernels.py
which has --backend reference (hardcoded reference impls) and
--backend llm (Bedrock-driven, host-verified per op). Splitting them keeps
this stage purely deterministic and lets the LLM kernel pass evolve
independently behind the stable kernel ABI.
"""

from __future__ import annotations

import argparse
import json
import os
from typing import Any

import numpy as np


HEADER = "/* @generated by agents/pipeline/generate_skeleton.py — do not edit. */"


def _c_ident(name: str) -> str:
    return name.replace(".", "_").replace("-", "_")


def _f32(x: float) -> str:
    """Format a float32 value as a C float literal (round-trip safe).

    Always emits a decimal point or exponent before the `f` suffix so the
    compiler reads it as a float (not an integer with an illegal suffix).
    """
    f = float(np.float32(x))
    if np.isnan(f):
        return "(0.0f/0.0f)"
    if np.isinf(f):
        return "(1.0f/0.0f)" if f > 0 else "(-1.0f/0.0f)"
    s = f"{f:.9g}"
    # `g` may print "0", "1", "-2" with no decimal/exponent — append ".0"
    # so the `f` suffix binds to a floating literal.
    if "." not in s and "e" not in s and "E" not in s and "n" not in s:
        s += ".0"
    return s + "f"


def _array_lines(arr: np.ndarray, per_line: int = 8) -> list[str]:
    flat = arr.astype(np.float32).reshape(-1)
    out: list[str] = []
    for i in range(0, len(flat), per_line):
        chunk = flat[i : i + per_line]
        out.append("    " + ", ".join(_f32(v) for v in chunk) + ",")
    return out


def _array_lines_int(arr: np.ndarray, per_line: int = 16) -> list[str]:
    """Format an integer array as lines of comma-separated decimal literals."""
    flat = arr.reshape(-1)
    out: list[str] = []
    for i in range(0, len(flat), per_line):
        chunk = flat[i : i + per_line]
        out.append("    " + ", ".join(str(int(v)) for v in chunk) + ",")
    return out


# Map our IR dtype tags to C scalar types (used everywhere — buffer decls,
# run_model signature, weights.h, test_io.h).
_DTYPE_TO_C = {
    "f32": "float",
    "i8":  "int8_t",
    "i32": "int32_t",
}


def _dtype_to_c(dtype: str) -> str:
    if dtype not in _DTYPE_TO_C:
        raise NotImplementedError(f"unknown IR dtype: {dtype}")
    return _DTYPE_TO_C[dtype]


def _np_to_c_dtype(np_dtype) -> tuple[str, str]:
    """(c_type, ir_dtype_tag) for a numpy weight blob's dtype."""
    if np_dtype == np.float32:
        return "float", "f32"
    if np_dtype == np.int8:
        return "int8_t", "i8"
    if np_dtype == np.int32:
        return "int32_t", "i32"
    raise NotImplementedError(f"unsupported weight dtype: {np_dtype}")


def _prod(shape: list[int]) -> int:
    n = 1
    for s in shape:
        n *= int(s)
    return n


def _buf_name(tensor: str) -> str:
    return f"buf_{_c_ident(tensor)}"


def emit_weights(weights: dict[str, np.ndarray], out_dir: str) -> None:
    keys = sorted(weights.keys())
    h_lines = [HEADER, "#pragma once", "",
               "#include <stdint.h>",
               "", "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    for k in keys:
        ident = _c_ident(k)
        c_type, _ = _np_to_c_dtype(weights[k].dtype)
        size = weights[k].size
        h_lines.append(f"extern const {c_type} {ident}[{size}];")
    h_lines += ["", "#ifdef __cplusplus", "}", "#endif", ""]
    with open(os.path.join(out_dir, "weights.h"), "w") as f:
        f.write("\n".join(h_lines))

    c_lines = [HEADER, "#include <stdint.h>", '#include "weights.h"', ""]
    for k in keys:
        ident = _c_ident(k)
        arr = weights[k]
        c_type, _ = _np_to_c_dtype(arr.dtype)
        c_lines.append(f"const {c_type} {ident}[{arr.size}] = {{")
        if arr.dtype == np.float32:
            c_lines += _array_lines(arr)
        else:
            c_lines += _array_lines_int(arr)
        c_lines.append("};")
        c_lines.append("")
    with open(os.path.join(out_dir, "weights.c"), "w") as f:
        f.write("\n".join(c_lines))


def _shape_str(op: dict) -> str:
    """Stable, parseable per-op shape string for the profile CSV."""
    sh = op.get("shape", {})
    return ";".join(f"{k}={sh[k]}" for k in sh)


def emit_model(ir: dict[str, Any], out_dir: str) -> None:
    in_tensor = ir["input"]["tensor"]
    out_field = ir["output"]
    out_tensors_list: list[str] = (
        list(out_field["tensors"]) if out_field.get("tensors") else [out_field["tensor"]]
    )
    tensors = ir["tensors"]
    in_size = _prod(tensors[in_tensor]["shape"])
    in_c_type = _dtype_to_c(tensors[in_tensor]["dtype"])
    # All outputs must share a dtype (we concatenate into one output buffer).
    out_dtypes = {tensors[t]["dtype"] for t in out_tensors_list}
    if len(out_dtypes) != 1:
        raise NotImplementedError(
            f"multi-output models with mixed dtypes not supported: {out_dtypes}"
        )
    out_c_type = _dtype_to_c(next(iter(out_dtypes)))
    # Multi-output: concatenate outputs into a single output buffer in order.
    out_sizes = [_prod(tensors[t]["shape"]) for t in out_tensors_list]
    out_offsets = [sum(out_sizes[:i]) for i in range(len(out_sizes))]
    out_size = sum(out_sizes)
    out_tensor_to_offset = dict(zip(out_tensors_list, out_offsets))

    # `view` ops (flatten / dropout-in-eval) do not generate a kernel call —
    # the output tensor name aliases the input's buffer. Build the alias map
    # before assigning intermediate buffers so views never get their own.
    aliases: dict[str, str] = {}
    def resolve_alias(name: str) -> str:
        seen: set[str] = set()
        while name in aliases:
            if name in seen:
                raise RuntimeError(f"alias cycle through {name}")
            seen.add(name)
            name = aliases[name]
        return name
    for op in ir["ops"]:
        if op["op"] == "view":
            aliases[op["outputs"][0]] = op["inputs"][0]

    # Number of ops that actually emit a kernel call (used to size the profile
    # record array).
    op_count = sum(1 for op in ir["ops"] if op["op"] != "view")

    h = f"""{HEADER}
#pragma once

#include <stddef.h>
#include <stdint.h>

#define MODEL_NAME           "{ir["name"]}"
#define MODEL_INPUT_SIZE     {in_size}
#define MODEL_OUTPUT_SIZE    {out_size}
#define MODEL_OP_COUNT       {op_count}
#define MODEL_QUANT          "{ir.get("quant", "fp32")}"

/* Model I/O scalar types — driven by the IR's per-tensor dtype field. The
 * harness's main.c uses these to declare its output buffer and parse types,
 * so the same main.c builds for fp32 and int8 unchanged. */
typedef {in_c_type}  model_input_t;
typedef {out_c_type} model_output_t;

#ifdef __cplusplus
extern "C" {{
#endif

/* Per-kernel profile record. Populated by run_model() — one entry per kernel
 * invocation, in execution order. `cycles` is rdcycle delta. */
typedef struct {{
    const char *name;   /* node name from IR (e.g. "fc1") */
    const char *op;     /* op kind (e.g. "linear", "linear_s8") */
    const char *shape;  /* shape descriptor, e.g. "M=1;K=16;N=32" */
    unsigned long cycles;
}} model_op_record_t;

void run_model(const model_input_t *input, model_output_t *output);

/* Returns pointer to the static profile array; *count gets the number of
 * records written by the most recent run_model() call. */
const model_op_record_t *model_profile_records(int *count);

#ifdef __cplusplus
}}
#endif
"""
    with open(os.path.join(out_dir, "model.h"), "w") as f:
        f.write(h)

    # Allocate one static buffer per intermediate tensor (skip input, any
    # final output tensor, and any tensor that is just a view alias).
    out_tensor_set = set(out_tensors_list)
    intermediates = [
        t for t in tensors
        if t != in_tensor and t not in out_tensor_set and t not in aliases
    ]
    buf_decls = []
    for t in intermediates:
        size = _prod(tensors[t]["shape"])
        c_type = _dtype_to_c(tensors[t]["dtype"])
        buf_decls.append(f"static {c_type} {_buf_name(t)}[{size}];")

    def ptr_for(tensor: str, role: str) -> str:
        tensor = resolve_alias(tensor)
        if tensor == in_tensor:
            return "input"
        if tensor in out_tensor_to_offset:
            off = out_tensor_to_offset[tensor]
            return "output" if off == 0 else f"(output + {off})"
        return _buf_name(tensor)

    call_blocks: list[str] = []
    for op in ir["ops"]:
        if op["op"] == "view":
            # No-op at runtime — buffer alias was set above.
            continue
        out_ptr = ptr_for(op["outputs"][0], "out")
        shape_lit = _shape_str(op)
        if op["op"] == "linear":
            in_ptr = ptr_for(op["inputs"][0], "in")
            w = _c_ident(op["weight"])
            b = _c_ident(op["bias"]) if op.get("bias") else "NULL"
            sh = op["shape"]
            call = (
                f"kernel_linear({in_ptr}, {w}, {b}, {out_ptr}, "
                f"{sh['M']}, {sh['K']}, {sh['N']})"
            )
        elif op["op"] == "relu":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_relu({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "elu":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            alpha = op.get("alpha", 1.0)
            call = f"kernel_elu({in_ptr}, {out_ptr}, {n}, {_f32(alpha)})"
        elif op["op"] == "conv2d":
            in_ptr = ptr_for(op["inputs"][0], "in")
            w = _c_ident(op["weight"])
            b = _c_ident(op["bias"]) if op.get("bias") else "NULL"
            sh = op["shape"]
            call = (
                f"kernel_conv2d({in_ptr}, {w}, {b}, {out_ptr}, "
                f"{sh['N']}, {sh['IC']}, {sh['IH']}, {sh['IW']}, "
                f"{sh['OC']}, {sh['KH']}, {sh['KW']}, "
                f"{sh['SH']}, {sh['SW']}, {sh['PH']}, {sh['PW']})"
            )
        elif op["op"] == "maxpool2d":
            in_ptr = ptr_for(op["inputs"][0], "in")
            sh = op["shape"]
            call = (
                f"kernel_maxpool2d({in_ptr}, {out_ptr}, "
                f"{sh['N']}, {sh['C']}, {sh['IH']}, {sh['IW']}, "
                f"{sh['KH']}, {sh['KW']}, {sh['SH']}, {sh['SW']})"
            )
        elif op["op"] == "add":
            a_ptr = ptr_for(op["inputs"][0], "in")
            b_ptr = ptr_for(op["inputs"][1], "in")
            n = op["shape"]["n"]
            call = f"kernel_add({a_ptr}, {b_ptr}, {out_ptr}, {n})"
        elif op["op"] == "batchnorm2d":
            in_ptr = ptr_for(op["inputs"][0], "in")
            s = _c_ident(op["weight"])
            b = _c_ident(op["bias"])
            sh = op["shape"]
            call = (
                f"kernel_batchnorm2d({in_ptr}, {s}, {b}, {out_ptr}, "
                f"{sh['N']}, {sh['C']}, {sh['H']}, {sh['W']})"
            )
        elif op["op"] == "sigmoid":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_sigmoid({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "linear_s8":
            in_ptr = ptr_for(op["inputs"][0], "in")
            w = _c_ident(op["weight"])
            b = _c_ident(op["bias"]) if op.get("bias") else "NULL"
            sh = op["shape"]
            q = op["quant"]
            call = (
                f"kernel_linear_s8({in_ptr}, {w}, {b}, {out_ptr}, "
                f"{sh['M']}, {sh['K']}, {sh['N']}, "
                f"{q['input_offset']}, {q['filter_offset']}, "
                f"{q['output_offset']}, "
                f"{q['output_multiplier']}, {q['output_shift']}, "
                f"{q['activation_min']}, {q['activation_max']})"
            )
        elif op["op"] == "relu_s8":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            call = f"kernel_relu_s8({in_ptr}, {out_ptr}, {n})"
        elif op["op"] == "conv2d_s8":
            in_ptr = ptr_for(op["inputs"][0], "in")
            w = _c_ident(op["weight"])
            b = _c_ident(op["bias"]) if op.get("bias") else "NULL"
            sh = op["shape"]
            q = op["quant"]
            call = (
                f"kernel_conv2d_s8({in_ptr}, {w}, {b}, {out_ptr}, "
                f"{sh['N']}, {sh['IC']}, {sh['IH']}, {sh['IW']}, "
                f"{sh['OC']}, {sh['KH']}, {sh['KW']}, "
                f"{sh['SH']}, {sh['SW']}, {sh['PH']}, {sh['PW']}, "
                f"{q['input_offset']}, {q['filter_offset']}, "
                f"{q['output_offset']}, "
                f"{q['output_multiplier']}, {q['output_shift']}, "
                f"{q['activation_min']}, {q['activation_max']})"
            )
        elif op["op"] == "maxpool2d_s8":
            in_ptr = ptr_for(op["inputs"][0], "in")
            sh = op["shape"]
            call = (
                f"kernel_maxpool2d_s8({in_ptr}, {out_ptr}, "
                f"{sh['N']}, {sh['C']}, {sh['IH']}, {sh['IW']}, "
                f"{sh['KH']}, {sh['KW']}, {sh['SH']}, {sh['SW']})"
            )
        elif op["op"] == "add_s8":
            a_ptr = ptr_for(op["inputs"][0], "in")
            b_ptr = ptr_for(op["inputs"][1], "in")
            n = op["shape"]["n"]
            q = op["quant"]
            call = (
                f"kernel_add_s8({a_ptr}, {b_ptr}, {out_ptr}, {n}, "
                f"{_f32(q['scale_a'])}, {_f32(q['scale_b'])}, "
                f"{_f32(q['scale_out'])}, "
                f"{q['activation_min']}, {q['activation_max']})"
            )
        elif op["op"] == "batchnorm2d_s8":
            in_ptr = ptr_for(op["inputs"][0], "in")
            s = _c_ident(op["weight"])
            b = _c_ident(op["bias"])
            sh = op["shape"]
            q = op["quant"]
            call = (
                f"kernel_batchnorm2d_s8({in_ptr}, {s}, {b}, {out_ptr}, "
                f"{sh['N']}, {sh['C']}, {sh['H']}, {sh['W']}, "
                f"{_f32(q['scale_in'])}, {_f32(q['scale_out'])}, "
                f"{q['activation_min']}, {q['activation_max']})"
            )
        elif op["op"] == "sigmoid_s8":
            in_ptr = ptr_for(op["inputs"][0], "in")
            n = op["shape"]["n"]
            q = op["quant"]
            call = (
                f"kernel_sigmoid_s8({in_ptr}, {out_ptr}, {n}, "
                f"{_f32(q['scale_in'])}, {_f32(q['scale_out'])}, "
                f"{q['activation_min']}, {q['activation_max']})"
            )
        else:
            raise NotImplementedError(f"unsupported op {op['op']}")
        call_blocks.append(
            f'    {{\n'
            f'        unsigned long _s = rdcycle();\n'
            f'        {call};\n'
            f'        unsigned long _e = rdcycle();\n'
            f'        model_op_records_[model_op_n_].name   = "{op["name"]}";\n'
            f'        model_op_records_[model_op_n_].op     = "{op["op"]}";\n'
            f'        model_op_records_[model_op_n_].shape  = "{shape_lit}";\n'
            f'        model_op_records_[model_op_n_].cycles = _e - _s;\n'
            f'        model_op_n_++;\n'
            f'    }}'
        )

    c = f"""{HEADER}
#include <stddef.h>
#include <stdint.h>
#include "model.h"
#include "kernels.h"
#include "weights.h"

/* RISC-V cycle counter: 1-instruction read of the mcycle CSR. */
static inline unsigned long rdcycle(void)
{{
    unsigned long cc;
    __asm__ volatile("rdcycle %0" : "=r"(cc));
    return cc;
}}

{chr(10).join(buf_decls)}

static model_op_record_t model_op_records_[MODEL_OP_COUNT];
static int model_op_n_;

void run_model(const model_input_t *input, model_output_t *output) {{
    model_op_n_ = 0;
{chr(10).join(call_blocks)}
}}

const model_op_record_t *model_profile_records(int *count) {{
    *count = model_op_n_;
    return model_op_records_;
}}
"""
    with open(os.path.join(out_dir, "model.c"), "w") as f:
        f.write(c)


def emit_test_io(io_npz: str, out_dir: str) -> None:
    data = np.load(io_npz)
    inp = data["input"].reshape(-1)
    out = data["output"].reshape(-1)
    in_c, _ = _np_to_c_dtype(inp.dtype)
    out_c, _ = _np_to_c_dtype(out.dtype)
    lines = [
        HEADER,
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"#define MODEL_TEST_INPUT_LEN  {inp.size}",
        f"#define MODEL_TEST_OUTPUT_LEN {out.size}",
        "",
        f"static const {in_c} model_test_input[{inp.size}] = {{",
    ]
    if inp.dtype == np.float32:
        lines += _array_lines(inp)
    else:
        lines += _array_lines_int(inp)
    lines += ["};", ""]
    lines.append(f"/* Reference output (host-side compare; not used at runtime). */")
    lines.append(f"static const {out_c} model_test_golden[{out.size}] = {{")
    if out.dtype == np.float32:
        lines += _array_lines(out)
    else:
        lines += _array_lines_int(out)
    lines += ["};", ""]
    with open(os.path.join(out_dir, "test_io.h"), "w") as f:
        f.write("\n".join(lines))


def generate(ir_path: str, weights_path: str, io_path: str, out_dir: str) -> None:
    os.makedirs(out_dir, exist_ok=True)
    with open(ir_path) as f:
        ir = json.load(f)
    weights = dict(np.load(weights_path))

    emit_weights(weights, out_dir)
    emit_model(ir, out_dir)
    emit_test_io(io_path, out_dir)

    files = ["weights.h", "weights.c", "model.h", "model.c", "test_io.h"]
    for fn in files:
        print(f"wrote {os.path.join(out_dir, fn)}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ir", required=True, help="graph.json")
    ap.add_argument("--weights", required=True, help="weights.npz")
    ap.add_argument("--io", required=True, help="io.npz")
    ap.add_argument("--out-dir", required=True, help="harness src/ dir")
    args = ap.parse_args()
    generate(args.ir, args.weights, args.io, args.out_dir)


if __name__ == "__main__":
    main()
