"""Emit a multi-network main.c that walks an XPU-RT dispatch table.

Companion to ``ingest_xpurt_schedule`` (which produces the C dispatch
table). Together they close the round trip:

    XPU-RT schedule.json
        -> ingest_xpurt_schedule  -> <name>_dispatch_table.{h,c}
        -> generate_xpurt_main    -> <name>_main.c
        -> west build (harness_multi)
        -> spike

The generated main:

    1. Creates one pthreadpool (worker count from AGENTS_POOL_THREADS).
    2. Resets every involved model's profile counter.
    3. Walks the dispatch table in start_time order, dispatching each
       entry to ``MODEL_<NET>_DISPATCH_FNS[entry.dispatch_id]`` with the
       per-network state it shares across all instances of that network.
    4. Prints each network's final output between the standard
       ``=== AGENTS_OUTPUT_BEGIN [<network>] ===`` markers so
       ``spike_runner`` can verify against the golden.

The current walker is sequential (`for i in 0..n-1`). Cross-dispatch
parallelism + k_sem-driven sync (task #61) is left as the natural
follow-up — once that lands, only the loop body changes here.
"""

from __future__ import annotations

import argparse
import json
import os


HEADER = "/* @generated by agents/pipeline/generate_xpurt_main.py — do not edit. */"


def _c_ident(name: str) -> str:
    return name.replace(".", "_").replace("-", "_")


def _emit(networks: list[str], schedule_name: str,
          dispatch_table_header: str,
          core_kinds: list[str]) -> str:
    """Render xpurt_main.c source.

    `networks` is the ordered list of distinct network names the
    schedule references; `core_kinds` is the ordered list of distinct
    core_kind values (one Zephyr worker thread per kind, pinned via
    pthread_attr_setaffinity_np)."""
    inc_lines: list[str] = []
    state_decls: list[str] = []
    state_inits: list[str] = []
    output_buf_decls: list[str] = []
    reset_calls: list[str] = []
    branch_lines: list[str] = []
    print_blocks: list[str] = []
    wall_decls: list[str] = []

    for net in networks:
        mid = _c_ident(net)
        umid = mid.upper()
        inc_lines.append(f'#include "{net}_model.h"')
        inc_lines.append(f'#include "{net}_test_io.h"')

        output_buf_decls.append(
            f"static model_{mid}_output_t out_{mid}[MODEL_{umid}_OUTPUT_SIZE];"
        )
        state_decls.append(f"    model_{mid}_state_t s_{mid};")
        wall_decls.append(f"    unsigned long wall_start_{mid} = 0;")
        state_inits.append(
            f"    s_{mid}.input  = model_{mid}_test_input;\n"
            f"    s_{mid}.output = out_{mid};\n"
            f"    s_{mid}.pool   = (void *)pool;"
        )
        reset_calls.append(f"    model_{mid}_reset_profile();")
        branch_lines.append(
            f'        if (e_->network[0] == \'{net[0]}\' && '
            f'strcmp(e_->network, "{net}") == 0) {{\n'
            f"            if (e_->dispatch_id == 0) {{\n"
            f"                model_{mid}_reset_profile();\n"
            f"                wall_start_{mid} = (unsigned long)k_cycle_get_64();\n"
            f"            }}\n"
            f"#ifdef AGENTS_XPURT_TRACE\n"
            f"            xpurt_trace[i_].start_cycles =\n"
            f"                (uint64_t)k_cycle_get_64() - run_t0;\n"
            f"#endif\n"
            f"            MODEL_{umid}_DISPATCH_FNS[e_->dispatch_id](&s_{mid});\n"
            f"#ifdef AGENTS_XPURT_TRACE\n"
            f"            xpurt_trace[i_].end_cycles =\n"
            f"                (uint64_t)k_cycle_get_64() - run_t0;\n"
            f"            xpurt_trace[i_].worker_kind_idx = my_kind_idx;\n"
            f"#endif\n"
            f"            if (e_->dispatch_id == MODEL_{umid}_OP_COUNT - 1) {{\n"
            f"                model_{mid}_set_wall_cycles(\n"
            f"                    (unsigned long)k_cycle_get_64() - wall_start_{mid});\n"
            f"            }}\n"
            f"            k_sem_give(&completion_sems[i_]);\n"
            f"            continue;\n"
            f"        }}"
        )
        print_blocks.append(f"""\
    printf("=== AGENTS_OUTPUT_BEGIN [{net}] ===\\n");
    for (int i = 0; i < MODEL_{umid}_OUTPUT_SIZE; i++) {{
        printf("%.9g\\n", (double)out_{mid}[i]);
    }}
    printf("=== AGENTS_OUTPUT_END [{net}] ===\\n");
    {{
        int n_records = 0;
        const model_{mid}_op_record_t *records =
            model_{mid}_profile_records(&n_records);
        printf("=== AGENTS_PROFILE_BEGIN [{net}] ===\\n");
        printf("dispatch_id,name,op,shape,cycles\\n");
        for (int i = 0; i < n_records; i++) {{
            printf("%d,%s,%s,%s,%lu\\n",
                   records[i].dispatch_id,
                   records[i].name, records[i].op, records[i].shape,
                   records[i].cycles);
        }}
        printf("=== AGENTS_PROFILE_END [{net}] ===\\n");
    }}
    printf("=== AGENTS_WALL_CYCLES [{net}] === %lu\\n",
           model_{mid}_wall_cycles());""")

    upper = schedule_name.replace(".", "_").replace("-", "_").upper()

    # Build the per-(core_kind, instance, dispatch_id) dispatch branch.
    # Same matching predicate as before, just used inside a worker now.
    dispatch_branch = "\n".join(branch_lines)

    # One Zephyr worker thread per distinct core_kind. Each pins itself
    # to a hart (the entry's .hart) and pulls only entries whose
    # core_kind matches. Workers wait on per-entry k_sem completions for
    # data deps + time_dep edges; the master gives at the end.
    n_kinds = len(core_kinds)
    kind_strs = ", ".join(f'"{k}"' for k in core_kinds)

    return f"""{HEADER}
/*
 * Schedule-driven multi-network entry point with per-core-kind worker
 * threads. Each worker:
 *   1. Walks the XPU-RT-emitted dispatch table in start_time order,
 *      taking entries whose .core_kind matches its own kind.
 *   2. Before invoking, waits on k_sems posted by the producers of its
 *      .deps[] (intra-job data deps) and .time_dep_entry_id (cross-job
 *      ordering edges).
 *   3. After invoking, gives the entry's k_sem so consumers unblock.
 * Workers are pinned to harts via pthread_attr_setaffinity_np (Phase A
 * patch). The xnnpack-style pthreadpool is still here — parallel_<op>
 * wrappers inside dispatched kernels use it for intra-op parallelism.
 *
 * Outputs follow the same multi-line marker protocol as the
 * straight-line multi_main, so spike_runner verifies them against
 * PyTorch goldens unchanged.
 */

#define AGENTS_DISABLE_UNMANGLED

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <sched.h>
#include <pthreadpool.h>
#include <zephyr/kernel.h>      /* k_cycle_get_64, k_sem */
#include <zephyr/sys/reboot.h>

{chr(10).join(inc_lines)}
#include "{dispatch_table_header}"

{chr(10).join(output_buf_decls)}

/* picolibc memalign workaround — see generate_multi_main.py. */
void *memalign(size_t alignment, size_t size) {{ return aligned_alloc(alignment, size); }}
int posix_memalign(void **out, size_t alignment, size_t size)
{{
    void *p = aligned_alloc(alignment, size);
    if (p == NULL) {{ return 12; }}
    *out = p; return 0;
}}

/* Per-entry completion sem: posted once when the dispatch finishes;
 * dependents take it before invoking. Initialized as 0/1 (binary, but
 * grow the limit so multiple consumers can each take their own
 * "completed" reading without blocking each other). */
static struct k_sem completion_sems[{upper}_N_ENTRIES];

/* Network state shared across all dispatches/instances of one network.
 * Initialized in main() before workers start. */
{chr(10).join("static " + d.lstrip() for d in state_decls).rstrip()}

/* Per-network wall-clock timer state — written when the first/last
 * dispatch of an instance runs. The kind worker sets these because the
 * walker already routes by (network, dispatch_id). */
{chr(10).join("static " + d.lstrip() for d in wall_decls).rstrip()}

#ifdef AGENTS_XPURT_TRACE
/* Per-entry execution trace. Each slot is touched by exactly one
 * worker (the one whose core_kind matches) so concurrent writes never
 * overlap. Cycles are mtime-based (k_cycle_get_64) and offset against
 * `run_t0`, captured immediately before the first worker starts. The
 * host parser reconstructs (start_ms, end_ms) by dividing by the
 * configured clock_mhz. */
struct xpurt_trace_slot {{
    uint64_t start_cycles;
    uint64_t end_cycles;
    int      worker_kind_idx;   /* index into kinds[] */
}};
static struct xpurt_trace_slot xpurt_trace[{upper}_N_ENTRIES];
static uint64_t run_t0;
#endif

struct xpurt_worker_arg {{
    const char *kind;
    int hart;
    int kind_idx;
}};

static void *xpurt_worker(void *arg)
{{
    struct xpurt_worker_arg *wa = (struct xpurt_worker_arg *)arg;
    const char *my_kind = wa->kind;
#ifdef AGENTS_XPURT_TRACE
    int my_kind_idx = wa->kind_idx;
#endif
    /* Take entries that match `my_kind`, in start_time order. */
    for (int i_ = 0; i_ < {upper}_N_ENTRIES; i_++) {{
        const xpurt_sched_entry_t *e_ = &{upper}_TABLE[i_];
        if (strcmp(e_->core_kind, my_kind) != 0) continue;

        /* Wait for all data deps + the time_dep edge to complete. */
        for (int d = 0; d < e_->n_deps; d++) {{
            k_sem_take(&completion_sems[e_->deps[d]], K_FOREVER);
            k_sem_give(&completion_sems[e_->deps[d]]); /* re-post for other waiters */
        }}
        if (e_->time_dep_entry_id >= 0) {{
            k_sem_take(&completion_sems[e_->time_dep_entry_id], K_FOREVER);
            k_sem_give(&completion_sems[e_->time_dep_entry_id]);
        }}

{dispatch_branch}
        printf("xpurt: WARN unknown network %s in entry %d\\n",
               e_->network, e_->entry_id);
        /* Unknown network — give the sem anyway so we don't deadlock. */
        k_sem_give(&completion_sems[i_]);
    }}
    return NULL;
}}

int main(void)
{{
    printf("xpurt-runner: schedule={schedule_name} entries=%d kinds=%d on %s\\n",
           {upper}_N_ENTRIES, {n_kinds}, CONFIG_BOARD_TARGET);

#ifndef AGENTS_POOL_THREADS
#define AGENTS_POOL_THREADS 0
#endif
    pthreadpool_t pool = pthreadpool_create(AGENTS_POOL_THREADS);
    if (pool == NULL) {{
        printf("FATAL: pthreadpool_create returned NULL\\n");
        sys_reboot(SYS_REBOOT_COLD);
        return -1;
    }}
    printf("pthreadpool: %u threads (intra-op)\\n",
           (unsigned)pthreadpool_get_threads_count(pool));

{chr(10).join(state_inits)}

{chr(10).join(reset_calls)}

    /* Init completion sems — limit > 1 so multi-consumer give/take
     * doesn't bottleneck. */
    for (int i = 0; i < {upper}_N_ENTRIES; i++) {{
        k_sem_init(&completion_sems[i], 0, 64);
    }}

    /* One worker per distinct core_kind. Each pins itself to the first
     * matching entry's hart (good enough — assumes all entries of the
     * same kind share a hart, which is true for our singleton-machine
     * schedules; multi-hart-per-kind would need a per-hart subdivision). */
    static const char *kinds[] = {{ {kind_strs} }};
    static struct xpurt_worker_arg wargs[{n_kinds}];
    static pthread_t tids[{n_kinds}];
    static pthread_attr_t attrs[{n_kinds}];

#ifdef AGENTS_XPURT_TRACE
    /* All trace timestamps are recorded as offsets from this baseline,
     * captured just before the workers spawn. Avoids large absolute
     * cycle counts in the printed output. */
    run_t0 = (uint64_t)k_cycle_get_64();
#endif

    for (int k = 0; k < {n_kinds}; k++) {{
        int pinned_hart = -1;
        for (int i_ = 0; i_ < {upper}_N_ENTRIES; i_++) {{
            if (strcmp({upper}_TABLE[i_].core_kind, kinds[k]) == 0) {{
                pinned_hart = {upper}_TABLE[i_].hart;
                break;
            }}
        }}
        wargs[k].kind = kinds[k];
        wargs[k].hart = pinned_hart;
        wargs[k].kind_idx = k;

        pthread_attr_init(&attrs[k]);
#ifdef CONFIG_POSIX_THREADS_AFFINITY
        if (pinned_hart >= 0) {{
            cpu_set_t cs;
            CPU_ZERO(&cs);
            CPU_SET(pinned_hart, &cs);
            pthread_attr_setaffinity_np(&attrs[k], sizeof(cs), &cs);
        }}
#endif
        int rc = pthread_create(&tids[k], &attrs[k], xpurt_worker, &wargs[k]);
        if (rc != 0) {{
            printf("FATAL: pthread_create kind=%s rc=%d\\n", kinds[k], rc);
            sys_reboot(SYS_REBOOT_COLD);
            return -1;
        }}
        printf("xpurt: worker[%d] kind=%s pinned_hart=%d\\n",
               k, kinds[k], pinned_hart);
    }}

    /* Wait for every worker to drain. */
    for (int k = 0; k < {n_kinds}; k++) {{
        pthread_join(tids[k], NULL);
        pthread_attr_destroy(&attrs[k]);
    }}

#ifdef AGENTS_XPURT_TRACE
    /* Trace dump — one CSV row per scheduled entry, with the actual
     * mtime-cycle window the worker ran and the kind-index of the
     * worker that owned it. The host parser cross-references this
     * with the dispatch table for op/network/predicted-time fields. */
    printf("=== AGENTS_XPURT_TRACE_BEGIN ===\\n");
    printf("entry_id,network,instance,dispatch_id,op,name,core_kind,hart,"
           "predicted_start_ms,predicted_duration_ms,worker_kind_idx,"
           "actual_start_cycles,actual_end_cycles\\n");
    for (int i = 0; i < {upper}_N_ENTRIES; i++) {{
        const xpurt_sched_entry_t *e = &{upper}_TABLE[i];
        printf("%d,%s,%d,%d,%s,%s,%s,%d,%.6f,%.6f,%d,%llu,%llu\\n",
               e->entry_id, e->network, e->instance, e->dispatch_id,
               e->op, e->name, e->core_kind, e->hart,
               (double)e->start_time_ms, (double)e->duration_ms,
               xpurt_trace[i].worker_kind_idx,
               (unsigned long long)xpurt_trace[i].start_cycles,
               (unsigned long long)xpurt_trace[i].end_cycles);
    }}
    printf("=== AGENTS_XPURT_TRACE_END ===\\n");
#endif

{chr(10).join(print_blocks)}

    pthreadpool_destroy(pool);
    sys_reboot(SYS_REBOOT_COLD);
    return 0;
}}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--schedule", required=True,
                    help="path to the schedule.json (XPU-RT format)")
    ap.add_argument("--out", required=True,
                    help="path to write xpurt_main.c")
    ap.add_argument("--name", required=True,
                    help="schedule name — must match the --name passed to "
                         "ingest_xpurt_schedule (drives the table symbol prefix)")
    ap.add_argument("--dispatch-table-header", required=True,
                    help="basename of the .h emitted by ingest_xpurt_schedule "
                         "(included from xpurt_main.c)")
    ap.add_argument("--core-kinds", default="rvv,scalar",
                    help="comma list of distinct core_kind values the schedule "
                         "uses — must match the --cpu-p-kind / --cpu-e-kind "
                         "passed to ingest_xpurt_schedule. One worker thread "
                         "is spawned per kind. (default: rvv,scalar)")
    args = ap.parse_args()

    with open(args.schedule) as f:
        sched = json.load(f)
    networks: list[str] = []
    seen: set[str] = set()
    for d in sched["dispatches"].values():
        net = d["job_name"].rstrip("0123456789")  # strip instance suffix
        if net not in seen:
            seen.add(net)
            networks.append(net)

    core_kinds = [k.strip() for k in args.core_kinds.split(",") if k.strip()]
    if not core_kinds:
        raise SystemExit("--core-kinds must be a non-empty comma list")

    src = _emit(networks, args.name, args.dispatch_table_header, core_kinds)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(src)
    print(f"wrote {args.out}  (networks: {networks} kinds: {core_kinds})")


if __name__ == "__main__":
    main()
