CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_GPIO=y

# Enable ST HAL module so the VL53L1X driver can be built
CONFIG_VL53L1X=y
CONFIG_VL53L1X_INTERRUPT_MODE=n

# Enable float support in printf (picolibc)
CONFIG_PICOLIBC_IO_FLOAT=y