import json
import os
import argparse

def generate_dronet_header(layers, header_path, header_guard="DRONET_H"):
    """
    Writes a C header (`dronet.h`) with muriscv-nn dims and params structs for each layer.
    """
    lines = []
    lines.append(f"#ifndef {header_guard}")
    lines.append(f"#define {header_guard}")
    lines.append("")
    lines.append("// AUTO-GENERATED by generate_header.py")
    lines.append("#include <muriscv_nn_types.h>")
    lines.append("")

    def to4(s):
        if len(s) == 4:
            return s
        elif len(s) == 2:
            return (s[0], 1, 1, s[1])
        else:
            raise ValueError(f"Unsupported shape: {s}")

    for idx, L in enumerate(layers):
        t = L['type']
        name = L['name']
        lines.append(f"// Layer {idx}: {t} ({name})")

        # bias dims if needed
        if t in ("Conv2d", "Linear"):
            out_shape = to4(L['out_shape'])
            out_dim = out_shape[-1]
            lines.append(f"static const muriscv_nn_dims layer{idx}_bias_dims = {{ .n = {out_dim}, .h = 0, .w = 0, .c = 0 }};")

        # handle Add separately
        if t == "Add":
            # elementwise add dims: two inputs and one output
            in0 = to4(L['in_shape_0'])
            in1 = to4(L['in_shape_1'])
            out0 = to4(L['out_shape'])
            lines.append(
                f"static const muriscv_nn_dims layer{idx}_input1_dims = {{ .n = {in0[0]}, .h = {in0[1]}, .w = {in0[2]}, .c = {in0[3]} }};"
            )
            lines.append(
                f"static const muriscv_nn_dims layer{idx}_input2_dims = {{ .n = {in1[0]}, .h = {in1[1]}, .w = {in1[2]}, .c = {in1[3]} }};"
            )
            lines.append(
                f"static const muriscv_nn_dims layer{idx}_output_dims = {{ .n = {out0[0]}, .h = {out0[1]}, .w = {out0[2]}, .c = {out0[3]} }};"
            )
            lines.append("")
            continue

        # dims for conv/pool/linear/relu/sigmoid
        in_n, in_h, in_w, in_c = to4(L['in_shape'])
        out_n, out_h, out_w, out_c = to4(L['out_shape'])
        lines.append(f"static const muriscv_nn_dims layer{idx}_input_dims  = {{ .n = {in_n}, .h = {in_h}, .w = {in_w}, .c = {in_c} }};")
        lines.append(f"static const muriscv_nn_dims layer{idx}_output_dims = {{ .n = {out_n}, .h = {out_h}, .w = {out_w}, .c = {out_c} }};")

        if t == "Conv2d":
            k_h, k_w = L['kernel_size']
            s_h, s_w = L['stride']; p_h, p_w = L['padding']; d_h, d_w = L.get('dilation', (1,1))
            lines.append(f"static const muriscv_nn_dims layer{idx}_filter_dims = {{ .n = {out_c}, .h = {k_h}, .w = {k_w}, .c = {in_c} }};")
            lines.append(f"static const muriscv_nn_conv_params layer{idx}_conv_params = {{")
            lines.append("    .input_offset  = 0,")
            lines.append("    .output_offset = 0,")
            lines.append(f"    .stride        = {{ .w = {s_w}, .h = {s_h} }},")
            lines.append(f"    .padding       = {{ .w = {p_w}, .h = {p_h} }},")
            lines.append(f"    .dilation      = {{ .w = {d_w}, .h = {d_h} }},")
            lines.append("    .activation    = { .min = INT8_MIN, .max = INT8_MAX },")
            lines.append("};")
        elif t == "MaxPool2d":
            k_h, k_w = L['kernel_size']
            s_h, s_w = L['stride']; p_h, p_w = L['padding']
            lines.append(f"static const muriscv_nn_dims layer{idx}_filter_dims = {{ .n = 0, .h = {k_h}, .w = {k_w}, .c = 0 }}; // H,W only")
            lines.append(f"static const muriscv_nn_pool_params layer{idx}_pool_params = {{")
            lines.append(f"    .stride     = {{ .w = {s_w}, .h = {s_h} }},")
            lines.append(f"    .padding    = {{ .w = {p_w}, .h = {p_h} }},")
            lines.append("    .activation = { .min = INT8_MIN, .max = INT8_MAX },")
            lines.append("};")
        elif t == "Linear":
            lines.append(f"static const muriscv_nn_dims layer{idx}_filter_dims = {{ .n = {in_c}, .h = 1, .w = 1, .c = {out_c} }};")
            lines.append(f"static const muriscv_nn_fc_params layer{idx}_fc_params = {{ .input_offset=0, .filter_offset=0, .output_offset=0, .activation={{ .min=INT8_MIN, .max=INT8_MAX }} }};")
        elif t == "ReLU":
            lines.append(f"// ReLU activation layer {idx}")
        elif t == "Sigmoid":
            lines.append(f"// Sigmoid activation layer {idx} (apply in software)")
            lines.append(f"// Sigmoid activation layer {idx} (apply in software)")
        lines.append("")

    lines.append(f"#endif // {header_guard}")
    with open(header_path, 'w') as f:
        f.write("\n".join(lines))
    print(f"Written C header to {header_path}")

def generate_params_header(layers, header_path, header_guard="DRONET_PARAMS_H"):
    """
    Writes a C header (`dronet_params.h`) with zero-initialized input, filter, bias,
    add-layer parameters, and output arrays for each layer.
    """
    import os

    lines = [
        f"#ifndef {header_guard}",
        f"#define {header_guard}",
        "",
        '#include "dronet.h"',
        ""
    ]

    def to4(shape):
        # normalize 2-D → 4-D
        if len(shape) == 4:
            return shape
        if len(shape) == 2:
            n, c = shape
            return (n, 1, 1, c)
        raise ValueError(f"Unsupported shape: {shape}")

    for idx, L in enumerate(layers):
        t = L['type']
        lines.append(f"// ------------------------------------------------------------")
        lines.append(f"// Layer {idx}: {t} parameters")
        lines.append(f"// ------------------------------------------------------------")

        # --- ADD layer ---
        if t == "Add":
            in0 = to4(L['in_shape_0'])
            in1 = to4(L['in_shape_1'])
            out = to4(L['out_shape'])
            blk = out[0] * out[1] * out[2] * out[3]

            lines.append(f"// Inputs for elementwise add")
            lines.append(f"static int8_t layer{idx}_input1_data[{in0[0]}*{in0[1]}*{in0[2]}*{in0[3]}] = {{0}};")
            lines.append(f"static int8_t layer{idx}_input2_data[{in1[0]}*{in1[1]}*{in1[2]}*{in1[3]}] = {{0}};")
            lines.append("")
            lines.append(f"// Output for elementwise add")
            lines.append(f"static int8_t layer{idx}_output_data[{blk}] = {{0}};")
            lines.append("")
            lines.append(f"// elementwise_add_s8 parameters")
            lines.append("/* function signature:")
            lines.append("   muriscv_nn_elementwise_add_s8(")
            lines.append("       const int8_t *input_1_vect,")
            lines.append("       const int8_t *input_2_vect,")
            lines.append("       const int32_t input_1_offset,")
            lines.append("       const int32_t input_1_mult,")
            lines.append("       const int32_t input_1_shift,")
            lines.append("       const int32_t input_2_offset,")
            lines.append("       const int32_t input_2_mult,")
            lines.append("       const int32_t input_2_shift,")
            lines.append("       const int32_t left_shift,")
            lines.append("       int8_t *output,")
            lines.append("       const int32_t out_offset,")
            lines.append("       const int32_t out_mult,")
            lines.append("       const int32_t out_shift,")
            lines.append("       const int32_t out_activation_min,")
            lines.append("       const int32_t out_activation_max,")
            lines.append("       const int32_t block_size);")
            lines.append("*/")
            lines.append(f"static const int32_t layer{idx}_add_input_1_offset     = 0;")
            lines.append(f"static const int32_t layer{idx}_add_input_1_mult       = 1;")
            lines.append(f"static const int32_t layer{idx}_add_input_1_shift      = 0;")
            lines.append(f"static const int32_t layer{idx}_add_input_2_offset     = 0;")
            lines.append(f"static const int32_t layer{idx}_add_input_2_mult       = 1;")
            lines.append(f"static const int32_t layer{idx}_add_input_2_shift      = 0;")
            lines.append(f"static const int32_t layer{idx}_add_left_shift         = 0;")
            lines.append(f"static const int32_t layer{idx}_add_out_offset         = 0;")
            lines.append(f"static const int32_t layer{idx}_add_out_mult           = 1;")
            lines.append(f"static const int32_t layer{idx}_add_out_shift          = 0;")
            lines.append(f"static const int32_t layer{idx}_add_activation_min     = INT8_MIN;")
            lines.append(f"static const int32_t layer{idx}_add_activation_max     = INT8_MAX;")
            lines.append("")
            continue

        # --- OTHER LAYERS: normalize shapes ---
        in_n, in_h, in_w, in_c = to4(L['in_shape'])
        out_n, out_h, out_w, out_c = to4(L['out_shape'])

        # Input buffer
        lines.append(f"// Input tensor for layer {idx}")
        lines.append(f"static int8_t layer{idx}_input_data[{in_n}*{in_h}*{in_w}*{in_c}] = {{0}};")
        lines.append("")

        if t == "Conv2d":
            k_h, k_w = L['kernel_size']
            # filter & bias
            lines.append(f"// Conv2d layer {idx}: filter and bias")
            lines.append(f"static int8_t  layer{idx}_filter_data[{out_c}*{in_c}*{k_h}*{k_w}] = {{0}};")
            lines.append(f"static int32_t layer{idx}_bias_data[{out_c}] = {{0}};")
            lines.append("")
            # **new** quant arrays + struct
            lines.append(f"// Conv2d layer {idx}: per-channel quantization params")
            lines.append(f"static int32_t layer{idx}_quant_mult[{out_c}]  = {{0}};")
            lines.append(f"static int32_t layer{idx}_quant_shift[{out_c}] = {{0}};")
            lines.append(
                f"static const muriscv_nn_per_channel_quant_params layer{idx}_quant_params = {{"
            )
            lines.append(f"    .multiplier = layer{idx}_quant_mult,")
            lines.append(f"    .shift      = layer{idx}_quant_shift,")
            lines.append("};")
            lines.append("")
        elif t == "Linear":
            # weights & bias
            lines.append(f"// FullyConnected layer {idx}: weights and bias")
            lines.append(f"static int8_t  layer{idx}_filter_data[{in_c}*{out_c}] = {{0}};")
            lines.append(f"static int32_t layer{idx}_bias_data[{out_c}] = {{0}};")
            lines.append(f"// FullyConnected layer {idx}: per-channel quantization params")
            lines.append(f"static int32_t layer{idx}_quant_mult[{out_c}]  = {{0}};")
            lines.append(f"static int32_t layer{idx}_quant_shift[{out_c}] = {{0}};")
            lines.append(
                f"static const muriscv_nn_quant_params layer{idx}_fc_quant_params = {{"
            )
            lines.append(f"    .multiplier = layer{idx}_quant_mult,")
            lines.append(f"    .shift      = layer{idx}_quant_shift,")
            lines.append(f"    .is_per_channel = 1,")
            lines.append("};")
            lines.append("")

        # Output buffer
        lines.append(f"// Output tensor for layer {idx}")
        lines.append(f"static int8_t layer{idx}_output_data[{out_n}*{out_h}*{out_w}*{out_c}] = {{0}};")
        lines.append("")

    lines.append(f"#endif // {header_guard}")

    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    with open(header_path, 'w') as f:
        f.write("\n".join(lines))
    print(f"Written Params header to {header_path}")



def generate_forward_files(layers, out_dir):
    import os

    # name → index lookup
    name_to_idx = {L['name']: i for i, L in enumerate(layers)}

    # --- dronet_forward.h ---
    hpath = os.path.join(out_dir, 'dronet_forward.h')
    hlines = [
        "#ifndef DRONET_FORWARD_H",
        "#define DRONET_FORWARD_H",
        "",
        "#ifdef __cplusplus",
        "extern \"C\" {",
        "#endif",
        "",
        "#include <muriscv_nn_types.h>",
        "#include <muriscv_nn_math_types.h>",
        "#include \"dronet.h\"",
        "#include \"dronet_params.h\"",
        "",
        "// Returns MURISCV_NN_SUCCESS or an error if any layer fails",
        "muriscv_nn_status dronet_forward(const int8_t *input_data,",
        "                                int8_t *output_data,",
        "                                muriscv_nn_context *ctx);",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        "#endif // DRONET_FORWARD_H",
        ""
    ]
    os.makedirs(os.path.dirname(hpath), exist_ok=True)
    with open(hpath, 'w') as f:
        f.write("\n".join(hlines))
    print(f"Written forward header to {hpath}")

    # --- dronet_forward.c ---
    cpath = os.path.join(out_dir, 'dronet_forward.c')
    clines = [
        "#include \"dronet_forward.h\"",
        "#include <muriscv_nn_functions.h>",
        "#include <string.h>",
        "#include <stdio.h>",
        "",
        "// rdcycle() for RISC-V cycle counting",
        "static inline unsigned long rdcycle(void) {",
        "    unsigned long cc;",
        "    __asm__ volatile(\"rdcycle %0\" : \"=r\"(cc));",
        "    return cc;",
        "}",
        "",
        "#define DEBUG",
        "",
        "muriscv_nn_status dronet_forward(const int8_t *input_data, int8_t *output_data, muriscv_nn_context *ctx) {",
        "    muriscv_nn_status status = MURISCV_NN_SUCCESS;",
        "",
        "   unsigned long start;",
        "   unsigned long end;",
        "",
    ]

    for idx, L in enumerate(layers):
        t   = L['type']
        src = L.get('input_from', 'input')
        # pick correct input buffer name
        if t == 'Add':
            src1, src2 = src.split(',')
            i1, i2 = name_to_idx[src1], name_to_idx[src2]
            in1 = f"layer{i1}_output_data"
            in2 = f"layer{i2}_output_data"
        else:
            in1 = "input_data" if src == 'input' else f"layer{name_to_idx[src]}_output_data"

        # start cycle counter
        clines.append(f"    // Layer {idx}: {t}")
        clines.append("    start = rdcycle();")

        if t == 'Conv2d':
            clines += [
                f"    status = muriscv_nn_convolve_wrapper_s8(ctx,",
                f"                                &layer{idx}_conv_params,",
                f"                                &layer{idx}_quant_params,",
                f"                                &layer{idx}_input_dims, {in1},",
                f"                                &layer{idx}_filter_dims, layer{idx}_filter_data,",
                f"                                &layer{idx}_bias_dims, layer{idx}_bias_data,",
                f"                                &layer{idx}_output_dims, layer{idx}_output_data);",
            ]
        elif t == 'MaxPool2d':
            clines += [
                f"    status = muriscv_nn_max_pool_s8(ctx,",
                f"                                &layer{idx}_pool_params,",
                f"                                &layer{idx}_input_dims, {in1},",
                f"                                &layer{idx}_filter_dims,",
                f"                                &layer{idx}_output_dims, layer{idx}_output_data);",
            ]
        elif t == 'ReLU':
            size = (L['out_shape'][1]*L['out_shape'][2]*L['out_shape'][3]
                    if len(L['out_shape'])==4 else L['out_shape'][-1])
            clines.append(f"    muriscv_nn_relu6_s8((int8_t*){in1}, {size});")
            clines.append("    status = MURISCV_NN_SUCCESS;")
        elif t == 'Add':
            blk = (L['out_shape'][1]*L['out_shape'][2]*L['out_shape'][3]
                   if len(L['out_shape'])==4 else L['out_shape'][-1])
            clines += [
                f"    status = muriscv_nn_elementwise_add_s8(",
                f"        {in1}, {in2},",
                f"        layer{idx}_add_input_1_offset, layer{idx}_add_input_1_mult, layer{idx}_add_input_1_shift,",
                f"        layer{idx}_add_input_2_offset, layer{idx}_add_input_2_mult, layer{idx}_add_input_2_shift,",
                f"        layer{idx}_add_left_shift,",
                f"        layer{idx}_output_data,",
                f"        layer{idx}_add_out_offset, layer{idx}_add_out_mult, layer{idx}_add_out_shift,",
                f"        layer{idx}_add_activation_min, layer{idx}_add_activation_max,",
                f"        {blk});",
            ]
        elif t == 'Linear':
            clines += [
                f"    status = muriscv_nn_fully_connected_wrapper_s8(ctx,",
                f"                                              &layer{idx}_fc_params,",
                f"                                              &layer{idx}_fc_quant_params,",
                f"                                              &layer{idx}_input_dims, {in1},",
                f"                                              &layer{idx}_filter_dims, layer{idx}_filter_data,",
                f"                                              &layer{idx}_bias_dims, layer{idx}_bias_data,",
                f"                                              &layer{idx}_output_dims, layer{idx}_output_data);",
            ]

        # check status
        clines.append("    if (status != MURISCV_NN_SUCCESS) return status;")
        # stop cycle counter + debug print
        clines += [
            "    end = rdcycle();",
            "#ifdef DEBUG",
            f"    printf(\"Layer {idx} ({t}) cycles: %lu\\n\", end - start);",
            "#endif",
            ""
        ]

    # complete
    clines += [
        "    return MURISCV_NN_SUCCESS;",
        "}",
        ""
    ]

    os.makedirs(os.path.dirname(cpath), exist_ok=True)
    with open(cpath, 'w') as f:
        f.write("\n".join(clines))
    print(f"Written forward source to {cpath}")




def main():
    parser = argparse.ArgumentParser(
        description="Generate dronet.h and dronet_params.h from layer-info JSON"
    )
    parser.add_argument(
        "--json-path", required=True,
        help="Path to input JSON file with layer info"
    )
    parser.add_argument(
        "--out-dir", required=True,
        help="Output directory for generated headers"
    )
    args = parser.parse_args()

    with open(args.json_path, 'r') as f:
        layers = json.load(f)

    os.makedirs(args.out_dir, exist_ok=True)
    # dronet.h
    dronet_h = os.path.join(args.out_dir, "dronet.h")
    generate_dronet_header(layers, dronet_h)
    # dronet_params.h
    params_h = os.path.join(args.out_dir, "dronet_params.h")
    generate_params_header(layers, params_h)
    generate_forward_files(layers, args.out_dir)



if __name__ == "__main__":
    main()
