#!/usr/bin/env python3
# Bake N ExecuTorch .pte models into ONE C translation unit + a registry table,
# so the riscv_executor_runner (built with -DMB_MULTI_MODEL) can run them all
# sequentially under a single boot / FireSim infrasetup. Each model's bytes go
# into the `network_model_sec` section (same as the single-model path); only the
# active model's activations occupy the runtime pool at a time.
#
#   python gen_multi_pte.py --out models_pte.c --header models_pte.h \
#       --model kb_63_conv=/path/a.pte --model kb_19_relu=/path/b.pte ...
import argparse
import binascii
import os

BYTES_PER_LINE = 32


def emit_array(fw, sym, data):
    fw.write(f'__attribute__((section("network_model_sec"), aligned(16)))\n'
             f'static const unsigned char {sym}[] = {{')
    hexs = binascii.hexlify(data).decode()
    for i in range(0, len(hexs), 2):
        if (i % (BYTES_PER_LINE * 2)) == 0:
            fw.write("\n")
        fw.write("0x" + hexs[i:i + 2] + ", ")
    fw.write("\n};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="output models_pte.c")
    ap.add_argument("--header", required=True, help="output models_pte.h")
    ap.add_argument("--model", action="append", default=[], required=True,
                    help="tag=/abs/path.pte (repeatable); tag is the run label")
    args = ap.parse_args()

    models = []  # (tag, path)
    for spec in args.model:
        tag, _, path = spec.partition("=")
        if not path or not os.path.isfile(path):
            raise SystemExit(f"--model {spec}: pte not found ({path})")
        models.append((tag, path))

    with open(args.header, "w") as fh:
        fh.write("/* @generated by gen_multi_pte.py */\n#pragma once\n"
                 "typedef struct { const char *name; const unsigned char *data;"
                 " unsigned int size; } mb_model_t;\n"
                 "extern const mb_model_t mb_models[];\n"
                 "extern const unsigned int mb_num_models;\n")

    total = 0
    with open(args.out, "w") as fw:
        fw.write('/* @generated by gen_multi_pte.py */\n#include "models_pte.h"\n\n')
        syms = []
        for i, (tag, path) in enumerate(models):
            with open(path, "rb") as fr:
                data = fr.read()
            sym = f"_mb_pte_{i}"
            emit_array(fw, sym, data)
            syms.append((tag, sym, len(data)))
            total += len(data)
        fw.write("\nconst mb_model_t mb_models[] = {\n")
        for tag, sym, n in syms:
            fw.write(f'    {{ "{tag}", {sym}, {n}u }},\n')
        fw.write("};\n")
        fw.write(f"const unsigned int mb_num_models = {len(syms)};\n")

    print(f"wrote {args.out} + {args.header}: {len(models)} models, "
          f"{total} bytes total ({total/2**20:.1f} MiB baked)")


if __name__ == "__main__":
    main()
